<?php
/*
 *
 * Action Bar Block Fields 
 * 
 */
return array(
    array(
        'key' => 'field_action_bar_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>Action Bar</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_action_bar_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'action_bar_heading',
        'type' => 'text',
        'instructions' => 'This heading is here for accessibility purposes only and will not be visible.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 'Important Links',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_action_bar_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'action_bar_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_action_bar_section'. $suffix,
        'label' => 'Sections',
        'name' => 'action_bar_section',
        'type' => 'repeater',
        'instructions' => 'You may have either 3 or 4 sections.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => 'field_section_heading'. $suffix,
        'min' => 3,
        'max' => 4,
        'layout' => 'block',
        'button_label' => 'Add Section',
        'sub_fields' => array(
            array(
                'key' => 'field_action_bar_section_heading'. $suffix,
                'label' => 'Heading',
                'name' => 'action_bar_section_heading',
                'type' => 'text',
                'instructions' => '46 character limit.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 46,
            ),
            array(
                'key' => 'field_action_bar_section_body'. $suffix,
                'label' => 'Body',
                'name' => 'action_bar_section_body',
                'type' => 'text',
                'instructions' => '67 character limit',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 67,
            ),
            array(
                'key' => 'field_action_bar_section_button_text'. $suffix,
                'label' => 'Button Text',
                'name' => 'action_bar_section_button_text',
                'type' => 'text',
                'instructions' => 'When the browser window is small, this button will be the only thing from this section that is displayed, so ensure that your Button Text will make sense on its own.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 31,
            ),
            array(
                'key' => 'field_action_bar_section_button_url'. $suffix,
                'label' => 'Button URL',
                'name' => 'action_bar_section_button_url',
                'type' => 'url',
                'instructions' => 'Include http:// or https://.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_action_bar_section_button_target'. $suffix,
                'label' => 'Open in New Window?',
                'name' => 'action_bar_section_button_target',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_action_bar_section_button_description'. $suffix,
                'label' => 'Button Link Description',
                'name' => 'action_bar_section_button_description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
    ),
);