<?php

declare(strict_types=1);

/*
 *
 * Content Block Fields 
 * 
 */
return [
    [
        'key' => 'field_content_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'message' => '<h2>UAMS Content Block</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ],
    [
        'key' => 'field_content_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'content_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_content_hide_heading'. $suffix,
        'label' => 'Hide Heading',
        'name' => 'content_hide_heading',
        'type' => 'true_false',
        'instructions' => 'The heading is necessary for page hierarchy. But it can be hidden from all but screen readers and search engines. This is <strong>strongly</strong> not recommended in most cases, as the visible heading provides a jumping-in point for users as they scan your page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ],
    [
        'key' => 'field_content_description'. $suffix,
        'label' => 'Content / Text',
        'name' => 'content_content',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions'=> [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
    ],
    [
        'key' => 'field_content_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'content_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'choices' => [
            'bg-auto' => 'Auto',
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ],
        'default_value' => [
            0 => 'bg-auto',
        ],
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ],
    [
        'key' => 'field_content_locked'. $suffix,
        'label' => 'Locked Content',
        'name' => '',
        'aria-label' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'message' => 'This content is locked. If you need something edited, please contact <a href="mailto:brent@uams.edu">Brent Passmore</a>.',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
        'acfe_settings' => '',
        'acfe_permissions' => [
            0 => 'editor',
        ],
    ],
    [
        'key' => 'field_content_geo_valid'. $suffix,
        'label' => 'GeoTargetingWP Installed?',
        'name' => 'geo_valid',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => 'hidden',
            'id' => '',
        ],
        'choices' => [
            'false' => 'False',
            'true' => 'True',
        ],
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 'false',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ],
    [
        'key' => 'field_content_regions'. $suffix,
        'label' => '<i class="dashicons dashicons-location-alt"></i> Region Filter',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => [
            [
                [
                    'field' => 'field_content_geo_valid'. $suffix,
                    'operator' => '==',
                    'value' => 'true',
                ],
            ],
        ],
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions'=> [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ],
    [
		'key' => 'field_content_geo'. $suffix,
		'label' => 'Regions',
		'name' => 'content_geo',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => [
            [
                [
                    'field' => 'field_content_geo_valid'. $suffix,
                    'operator' => '==',
                    'value' => 'true',
                ],
            ],
        ],
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
        'acfe_permissions'=> [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'choices' => [
            'include' => 'Include',
            'exclude' => 'Exclude',
        ],
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value'
    ],
    [
		'key' => 'field_content_geo_region'. $suffix,
		'label' => 'Regions',
		'name' => 'content_geo_region',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => [
			'width' => '',
			'class' => '',
			'id' => '',
		],
        'acfe_permissions'=> [
				0 => 'super_admin',
				1 => 'administrator',
			],
        'choices' => [
            'central' => 'Central',
            'northeast' => 'Northeast',
            'northwest' => 'Northwest',
            'southeast' => 'Southeast',
            'southwest' => 'Southwest',
        ],
        'default_value' => [
        ],
        'allow_null' => 0,
        'multiple' => 1,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'allow_custom' => 0,
        'placeholder' => '',
        'search_placeholder' => '',
    ],
];
