<?php
/*
 *
 * CTA Bar Block Fields 
 * 
 */
return array(
    array(
        'key' => 'field_cta_bar_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>UAMS Call-to-Action (CTA) Bar Block</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_cta_bar_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'cta_bar_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_cta_bar_body'. $suffix,
        'label' => 'Body',
        'name' => 'cta_bar_body',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
    ),
    array(
        'key' => 'field_cta_bar_button_text'. $suffix,
        'label' => 'Button Text',
        'name' => 'cta_bar_button_text',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_cta_bar_button_url'. $suffix,
        'label' => 'Button URL',
        'name' => 'cta_bar_button_url',
        'type' => 'link',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_cta_bar_button_text'. $suffix,
                    'operator' => '!=empty',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'array',
    ),
    // array(
    //     'key' => 'field_cta_bar_button_target'. $suffix,
    //     'label' => 'Open in New Window?',
    //     'name' => 'cta_bar_button_target',
    //     'type' => 'true_false',
    //     'instructions' => '',
    //     'required' => 0,
    //     'conditional_logic' => array(
    //         array(
    //             array(
    //                 'field' => 'field_cta_bar_button_text'. $suffix,
    //                 'operator' => '!=empty',
    //             ),
    //         ),
    //     ),
    //     'wrapper' => array(
    //         'width' => '',
    //         'class' => '',
    //         'id' => '',
    //     ),
    //     'message' => '',
    //     'default_value' => 0,
    //     'ui' => 1,
    //     'ui_on_text' => '',
    //     'ui_off_text' => '',
    // ),
    array(
        'key' => 'field_cta_bar_button_description'. $suffix,
        'label' => 'Button Link Description',
        'name' => 'cta_bar_button_description',
        'type' => 'text',
        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_cta_bar_button_text'. $suffix,
                    'operator' => '!=empty',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_cta_bar_layout'. $suffix,
        'label' => 'Layout',
        'name' => 'cta_bar_layout',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'cta-bar-centered' => 'Centered',
            'cta-bar-weighted' => 'Weighted',
        ),
        'default_value' => array(
            0 => 'cta-bar-centered',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_cta_bar_size'. $suffix,
        'label' => 'Size',
        'name' => 'cta_bar_size',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'normal' => 'Normal',
            'small' => 'Small',
        ),
        'default_value' => array(
            0 => 'normal',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_cta_bar_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'cta_bar_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_cta_bar_use_image'. $suffix,
        'label' => 'Use Background Image?',
        'name' => 'cta_bar_use_image',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_cta_bar_image'. $suffix,
        'label' => 'Image',
        'name' => 'cta_bar_image',
        'type' => 'image',
        'instructions' => 'Recommended image dimensions: 5120x2560. Minimum image dimensions: 1920x960. The image will be automatically cropped to a 2:1 aspect ratio.',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_cta_bar_use_image'. $suffix,
                    'operator' => '==',
                    'value' => '1',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => 1920,
        'min_height' => 960,
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
    ),
);