<?php
/*
 *
 * Gallery Block Fields 
 * 
 */
return array(
    array(
        'key' => 'field_gallery_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>UAMS Gallery Block</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_gallery_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'gallery_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_gallery_hide_heading'. $suffix,
        'label' => 'Hide Heading',
        'name' => 'gallery_hide_heading',
        'type' => 'true_false',
        'instructions' => 'The heading is necessary for page hierarchy. But it can be hidden from all but screen readers and search engines. This is not recommended in most cases.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_gallery_description'. $suffix,
        'label' => 'Description',
        'name' => 'gallery_description',
        'type' => 'wysiwyg',
        'instructions' => '(optional)',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
    ),
    array(
        'key' => 'field_gallery_columns'. $suffix,
        'label' => 'Number of Columns',
        'name' => 'gallery_columns',
        'type' => 'button_group',
        'instructions' => 'This will be the number of columns used on desktop browser sizes.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            2 => '2',
            3 => '3',
            4 => '4',
            6 => '6',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 3,
        'layout' => 'horizontal',
        'return_format' => 'value',
        'save_other_choice' => 0,
    ),
    array(
        'key' => 'field_gallery_images'. $suffix,
        'label' => 'Images',
        'name' => 'gallery_images',
        'type' => 'gallery',
        'instructions' => 'It is recommended that you select images that are of a similar aspect ratio.<br />Minimum dimensions: 1227x1635',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'insert' => 'append',
        'library' => 'all',
        'min' => 2,
        'max' => 6,
        'min_width' => '1227',
        'min_height' => '1635',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
    ),
    array(
        'key' => 'field_gallery_crop'. $suffix,
        'label' => 'Image Crop',
        'name' => 'gallery_crop',
        'type' => 'select',
        'instructions' => 'It is recommended that you select a crop option if your images are not all the same aspect ratio.<br />Choose the aspect ratio of the image crop. The remaining center portion will be visible.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            'none' => 'None',
            '1.7778' => '16:9 (landscape)',
            '1.3333' => '4:3 (landscape)',
            '1' => '1:1 (square)',
            '0.75' => '3:4 (portrait)',
        ),
        'default_value' => array(
            0 => 'none',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_gallery_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'gallery_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_gallery_modal'. $suffix,
        'label' => 'Include modal with larger version of image?',
        'name' => 'gallery_modal',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'message' => '',
        'default_value' => 1,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_gallery_more'. $suffix,
        'label' => 'Include link to something?',
        'name' => 'gallery_more',
        'type' => 'true_false',
        'instructions' => 'This could be used to link to more photos.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_gallery_more_text'. $suffix,
        'label' => 'Heading',
        'name' => 'gallery_more_text',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_gallery_more'. $suffix,
                    'operator' => '==',
                    'value' => '1',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => 'Would you like to see more photos like this?',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_gallery_more_button_text'. $suffix,
        'label' => 'Button Text',
        'name' => 'gallery_more_button_text',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_gallery_more'. $suffix,
                    'operator' => '==',
                    'value' => '1',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 'View More Photos',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_gallery_more_button_url'. $suffix,
        'label' => 'Button URL',
        'name' => 'gallery_more_button_url',
        'type' => 'link',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_gallery_more'. $suffix,
                    'operator' => '==',
                    'value' => '1',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'array',
    ),
    array(
        'key' => 'field_gallery_more_button_description'. $suffix,
        'label' => 'Button Link Description',
        'name' => 'gallery_more_button_description',
        'type' => 'text',
        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_gallery_more'. $suffix,
                    'operator' => '==',
                    'value' => '1',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_gallery_geo_valid'. $suffix,
        'label' => 'GeoTargetingWP Installed?',
        'name' => 'geo_valid',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => 'hidden',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            'false' => 'False',
            'true' => 'True',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 'false',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ),
    array(
        'key' => 'field_gallery_regions'. $suffix,
        'label' => '<i class="dashicons dashicons-location-alt"></i> Region Filter',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_gallery_geo_valid'. $suffix,
                    'operator' => '==',
                    'value' => 'true',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ),
    array(
		'key' => 'field_gallery_geo'. $suffix,
		'label' => 'Regions',
		'name' => 'gallery_geo',
		'type' => 'geot_field',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_gallery_geo_valid'. $suffix,
                    'operator' => '==',
                    'value' => 'true',
                ),
            ),
        ),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'acfe_permissions' => '',
		'geot_show' => 'city-regions',
		'geot_condition' => 'include',
		'geot_regions' => '',
		'geot_countries' => '',
	),
);