<?php
/*
 *
 * Gallery Block Fields 
 * 
 */
return array(
    array(
        'key' => 'field_gallery_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'gallery_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_gallery_hide_heading'. $suffix,
        'label' => 'Hide Heading',
        'name' => 'gallery_hide_heading',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_gallery_description'. $suffix,
        'label' => 'Description',
        'name' => 'gallery_description',
        'type' => 'wysiwyg',
        'instructions' => '(optional)',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
    ),
    array(
        'key' => 'field_gallery_columns'. $suffix,
        'label' => 'Number of Columns',
        'name' => 'gallery_columns',
        'type' => 'button_group',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            2 => '2',
            3 => '3',
            4 => '4',
            6 => '6',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 3,
        'layout' => 'horizontal',
        'return_format' => 'value',
        'save_other_choice' => 0,
    ),
    array(
        'key' => 'field_gallery_images'. $suffix,
        'label' => 'Images',
        'name' => 'gallery_images',
        'type' => 'gallery',
        'instructions' => 'It is recommended that you select images that are of a similar aspect ratio.<br />Minimum dimensions: 1227x1635',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'insert' => 'append',
        'library' => 'all',
        'min' => 2,
        'max' => 6,
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
    ),
    array(
        'key' => 'field_gallery_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'gallery_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
);