<?php
/*
 *
 * Image Side-by-side ACF Fields 
 * 
 */
return array(
    array(
        'key' => 'field_side_intro' . $suffix,
        'label' => '',
        'name' => 'field_side_intro',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>UAMS Side-by-Side Image &amp; Text Block</h2>',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_side_layout' . $suffix,
        'label' => 'Choose Text Layout',
        'name' => 'side_text_layout',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'body-only' => 'Body only',
            'link-list' => 'Body and Link List',
        ),
        'default_value' => array(
            0 => 'body-only',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_side_heading' . $suffix,
        'label' => 'Heading',
        'name' => 'side_heading',
        'type' => 'text',
        'instructions' => '50 character limit.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => 50,
    ),
    array(
        'key' => 'field_side_layout_body_text'. $suffix,
        'label' => 'Body',
        'name' => 'side_layout_body_text',
        'type' => 'textarea',
        'instructions' => '449 character limit.',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_side_layout'. $suffix,
                    'operator' => '==',
                    'value' => 'body-only',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => 449,
        'rows' => 6,
        'new_lines' => '',
    ),
    array(
        'key' => 'field_side_layout_link_text'. $suffix,
        'label' => 'Body',
        'name' => 'side_layout_link_text',
        'type' => 'textarea',
        'instructions' => '172 character limit.',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_side_layout'. $suffix,
                    'operator' => '==',
                    'value' => 'link-list',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => 172,
        'rows' => 3,
        'new_lines' => '',
    ),
    array(
        'key' => 'field_side_link_list'. $suffix,
        'label' => 'Link List',
        'name' => 'side_link_list',
        'type' => 'repeater',
        'instructions' => 'You may add up to six links. However, if you add a sixth link, the option for adding "and more" in the sixth position will be disabled.',
        'required' => 1,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_side_layout'. $suffix,
                    'operator' => '==',
                    'value' => 'link-list',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => 'field_side_link_list_text'. $suffix,
        'min' => 1,
        'max' => 6,
        'layout' => 'block',
        'button_label' => 'Add Link',
        'sub_fields' => array(
            array(
                'key' => 'field_side_link_list_text'. $suffix,
                'label' => 'Link Text',
                'name' => 'side_link_list_text',
                'type' => 'text',
                'instructions' => '40 character limit.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 40,
            ),
            array(
                'key' => 'field_side_link_list_url'. $suffix,
                'label' => 'Link URL',
                'name' => 'side_link_list_url',
                'type' => 'link',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_side_link_list_description'. $suffix,
                'label' => 'Link Description',
                'name' => 'side_link_list_description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
    ),
    array(
        'key' => 'field_side_link_include_more'. $suffix,
        'label' => 'Include "and more" at the end of the Link List?',
        'name' => 'side_link_include_more',
        'type' => 'true_false',
        'instructions' => 'This option is only available if you have 1-5 items in the link list.',
        'required' => 0,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_side_link_list'. $suffix,
                    'operator' => '<',
                    'value' => '6',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_side_cta'. $suffix,
        'label' => 'Call to Action Button',
        'name' => 'side_cta',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
            array(
                'key' => 'field_side_cta_text'. $suffix,
                'label' => 'Button Text',
                'name' => 'side_cta_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_side_cta_url'. $suffix,
                'label' => 'Button URL',
                'name' => 'side_cta_url',
                'type' => 'link',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_side_cta_text'. $suffix,
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            // array(
            //     'key' => 'field_side_cta_target'. $suffix,
            //     'label' => 'Open in New Window?',
            //     'name' => 'side_cta_target',
            //     'type' => 'true_false',
            //     'instructions' => '',
            //     'required' => 0,
            //     'conditional_logic' => 0,
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'message' => '',
            //     'default_value' => 0,
            //     'ui' => 1,
            //     'ui_on_text' => '',
            //     'ui_off_text' => '',
            // ),
            array(
                'key' => 'field_side_cta_description'. $suffix,
                'label' => 'Link Description',
                'name' => 'side_cta_description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_side_cta_text'. $suffix,
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
    ),
    array(
        'key' => 'field_side_image'. $suffix,
        'label' => 'Image Options',
        'name' => 'side_image',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
            array(
                'key' => 'field_side_image_image'. $suffix,
                'label' => 'Image',
                'name' => 'side_image_image',
                'type' => 'image',
                'instructions' => 'Recommended image dimensions: 2560x1440. Minimum image dimensions: 1920x1080. The image will be automatically cropped to a 16:9 aspect ratio.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => 1920,
                'min_height' => 1080,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_side_image_alt_text'. $suffix,
                'label' => 'Image Alt Text Override',
                'name' => 'side_image_alt_text',
                'type' => 'text',
                'instructions' => 'Alt text (alternative text) refers to invisible description of images which are read aloud to blind users on a screen reader. If you want to define alt text that is different from the alt text defined for this image in the media library, you can do so here.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 125,
            ),
            array(
                'key' => 'field_side_image_crop'. $suffix,
                'label' => 'Vertical Crop',
                'name' => 'side_image_crop',
                'type' => 'button_group',
                'instructions' => 'Your image will be cropped if necessary. Tell us if we should crop it from the top, middle, or bottom.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'top' => 'Top',
                    'center' => 'Center',
                    'bottom' => 'Bottom',
                ),
                'allow_null' => 0,
                'default_value' => 'center',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_side_image_anchor'. $suffix,
                'label' => 'Image Anchor Position',
                'name' => 'side_image_anchor',
                'type' => 'button_group',
                'instructions' => 'Where is the focus of your image content?',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Left',
                    'center' => 'Center',
                    'right' => 'Right',
                ),
                'allow_null' => 0,
                'default_value' => 'center',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
        ),
    ),
    array(
        'key' => 'field_side_image_position'. $suffix,
        'label' => 'Image & Text Position',
        'name' => 'side_image_position',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'left' => 'Image on Left, Text on Right',
            'right' => 'Image on Right, Text on Left',
        ),
        'default_value' => array(
            0 => 'left',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_side_image_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'side_image_background_color',
        'type' => 'select',
        'instructions' => 'This defines the background color of the text container.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
);