<?php
/*
 *
 * Stacked Image & Text Block Fields
 * 
 */
return array(
    array(
        'key' => 'field_link_list_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>Link List</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_link_list_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'link_list_heading',
        'type' => 'text',
        'instructions' => 'Even if this heading is hidden, it is necessary for accessibility.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_link_list_hide_heading'. $suffix,
        'label' => 'Hide Heading?',
        'name' => 'link_list_hide_heading',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_link_list_description'. $suffix,
        'label' => 'List Description',
        'name' => 'link_list_description',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 3,
        'new_lines' => '',
    ),
    array(
        'key' => 'field_link_list_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'link_list_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    // array(
    //     'key' => 'field_link_list_icons'. $suffix,
    //     'label' => 'Include Icons?',
    //     'name' => 'link_list_icons',
    //     'type' => 'true_false',
    //     'instructions' => '',
    //     'required' => 0,
    //     'conditional_logic' => 0,
    //     'wrapper' => array(
    //         'width' => '',
    //         'class' => '',
    //         'id' => '',
    //     ),
    //     'message' => '',
    //     'default_value' => 0,
    //     'ui' => 1,
    //     'ui_on_text' => '',
    //     'ui_off_text' => '',
    // ),
    array(
        'key' => 'field_link_list_section'. $suffix,
        'label' => 'Links',
        'name' => 'link_list_section',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => 'field_link_list_section_title'. $suffix,
        'min' => 1,
        'max' => 0,
        'layout' => 'block',
        'button_label' => 'Add Link',
        'sub_fields' => array(
            array(
                'key' => 'field_link_list_section_title'. $suffix,
                'label' => 'Link Title',
                'name' => 'link_list_section_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_link_list_section_body'. $suffix,
                'label' => 'Link Caption',
                'name' => 'link_list_section_body',
                'type' => 'text',
                'instructions' => 'This is the text displayed below the link title. This has a 90-character limit.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 90,
            ),
            array(
                'key' => 'field_link_list_section_url'. $suffix,
                'label' => 'Link URL',
                'name' => 'link_list_section_url',
                'type' => 'link',
                'instructions' => 'Include http:// or https://.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_link_list_section_description'. $suffix,
                'label' => 'Link Accessibility Description',
                'name' => 'link_list_section_description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". This text will not be displayed on the page. Describe the intent of the link, like "Learn more about the ABC Department".',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            // array(
            //     'key' => 'field_link_list_section_icon'. $suffix,
            //     'label' => 'Icon Class',
            //     'name' => 'link_list_section_icon',
            //     'type' => 'text',
            //     'instructions' => 'Copy the entire class provided by Fontawesome (https://fontawesome.com/icons). Example: "fas fa-dragon" (do not include the quotation marks).',
            //     'required' => 0,
            //     'conditional_logic' => 0,
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'default_value' => '',
            //     'placeholder' => '',
            //     'prepend' => '',
            //     'append' => '',
            //     'maxlength' => '',
            // ),
        ),
    ),
);