<?php
/*
 *
 * Stacked Image & Text Block Fields
 * 
 */
return array(
    array(
        'key' => 'field_link_list_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>UAMS Link List Block</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_link_list_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'link_list_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_link_list_description'. $suffix,
        'label' => 'List Description',
        'name' => 'link_list_description',
        'type' => 'textarea',
        'instructions' => 'This has a 518-character limit, but the recommended number of characters is 317 or fewer.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => 518,
        'rows' => 3,
        'new_lines' => '',
    ),
    array(
        'key' => 'field_link_list_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'link_list_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
            'bg-red' => 'Red',
            'bg-black' => 'Black',
            'bg-blue' => 'Blue',
            'bg-green' => 'Green',
            'bg-teal' => 'Teal',
            'bg-eggplant' => 'Eggplant',
            'bg-orange' => 'Orange',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    // array(
    //     'key' => 'field_link_list_icons'. $suffix,
    //     'label' => 'Include Icons?',
    //     'name' => 'link_list_icons',
    //     'type' => 'true_false',
    //     'instructions' => '',
    //     'required' => 0,
    //     'conditional_logic' => 0,
    //     'wrapper' => array(
    //         'width' => '',
    //         'class' => '',
    //         'id' => '',
    //     ),
    //     'message' => '',
    //     'default_value' => 0,
    //     'ui' => 1,
    //     'ui_on_text' => '',
    //     'ui_off_text' => '',
    // ),
    array(
        'key' => 'field_link_list_section'. $suffix,
        'label' => 'Links',
        'name' => 'link_list_section',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => 'field_link_list_section_title'. $suffix,
        'min' => 1,
        'max' => 0,
        'layout' => 'block',
        'button_label' => 'Add Link',
        'sub_fields' => array(
            array(
                'key' => 'field_link_list_section_title'. $suffix,
                'label' => 'Link Title',
                'name' => 'link_list_section_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_link_list_section_body'. $suffix,
                'label' => 'Link Caption',
                'name' => 'link_list_section_body',
                'type' => 'text',
                'instructions' => 'This is the text displayed below the link title. This has a 90-character limit.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 90,
            ),
            array(
                'key' => 'field_link_list_section_url'. $suffix,
                'label' => 'Link URL',
                'name' => 'link_list_section_url',
                'type' => 'link',
                'instructions' => 'Include http:// or https://.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_link_list_section_description'. $suffix,
                'label' => 'Link Accessibility Description',
                'name' => 'link_list_section_description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. Describe the intent of the link, like "Learn more about the ABC Department". It needs to be unique relative to the other links on this page (not reusing any other value for Link Title or Link Accessibility Description). <strong>Do not copy the Link Title value here</strong>.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            // array(
            //     'key' => 'field_link_list_section_icon'. $suffix,
            //     'label' => 'Icon Class',
            //     'name' => 'link_list_section_icon',
            //     'type' => 'text',
            //     'instructions' => 'Copy the entire class provided by Fontawesome (https://fontawesome.com/icons). Example: "fas fa-dragon" (do not include the quotation marks).',
            //     'required' => 0,
            //     'conditional_logic' => 0,
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'default_value' => '',
            //     'placeholder' => '',
            //     'prepend' => '',
            //     'append' => '',
            //     'maxlength' => '',
            // ),
        ),
    ),
    array(
        'key' => 'field_link_list_geo_valid'. $suffix,
        'label' => 'GeoTargetingWP Installed?',
        'name' => 'geo_valid',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => 'hidden',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'choices' => array(
            'false' => 'False',
            'true' => 'True',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 'false',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ),
    array(
        'key' => 'field_link_list_regions'. $suffix,
        'label' => '<i class="dashicons dashicons-location-alt"></i> Region Filter',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_link_list_geo_valid'. $suffix,
                    'operator' => '==',
                    'value' => 'true',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ),
    array(
		'key' => 'field_link_list_geo'. $suffix,
		'label' => 'Regions',
		'name' => 'link_list_geo',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_link_list_geo_valid'. $suffix,
                    'operator' => '==',
                    'value' => 'true',
                ),
            ),
        ),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
        'acfe_permissions' => '',
        'choices' => array(
            'include' => 'Include',
            'exclude' => 'Exclude',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value'
    ),
    array(
		'key' => 'field_link_list_geo_region'. $suffix,
		'label' => 'Regions',
		'name' => 'link_list_geo_region',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
        'acfe_permissions' => '',
        'choices' => array(
            'central' => 'Central',
            'northeast' => 'Northeast',
            'northwest' => 'Northwest',
            'southeast' => 'Southeast',
            'southwest' => 'Southwest',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 1,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'allow_custom' => 0,
        'placeholder' => '',
        'search_placeholder' => '',
    ),
);