<?php

declare(strict_types=1);

/*
 *
 * LiveWhale Calendar Block Fields
 *
 */
return [
    [
        'key' => 'field_livewhale_intro'.$suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'message' => '<h2>UAMS Livewhale Calendar Block</h2>',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
    ],
    [
        'key' => 'field_livewhale_heading'.$suffix,
        'label' => 'Heading',
        'name' => 'livewhale_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_livewhale_id'.$suffix,
        'label' => 'ID Number of Widget',
        'name' => 'livewhale_id',
        'type' => 'number',
        'instructions' => 'ex. ID=2 <code>(&lt;div class="lwcw" data-options="id=<b>2</b>&format=html"&gt;)</code>',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => 1,
        'max' => '',
        'step' => 1,
    ],
    [
        'key' => 'field_livewhale_background_color'.$suffix,
        'label' => 'Background Color',
        'name' => 'livewhale_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'choices' => [
            'bg-auto' => 'Auto',
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
        ],
        'default_value' => [
            0 => 'bg-auto',
        ],
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ],
    [
        'key' => 'field_livewhale_geo_valid'.$suffix,
        'label' => 'GeoTargetingWP Installed?',
        'name' => 'geo_valid',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => 'hidden',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'choices' => [
            'false' => 'False',
            'true' => 'True',
        ],
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 'false',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ],
    [
        'key' => 'field_livewhale_regions'.$suffix,
        'label' => '<i class="dashicons dashicons-location-alt"></i> Region Filter',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => [
            [
                [
                    'field' => 'field_livewhale_geo_valid'.$suffix,
                    'operator' => '==',
                    'value' => 'true',
                ],
            ],
        ],
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ],
    [
        'key' => 'field_livewhale_geo'.$suffix,
        'label' => 'Regions',
        'name' => 'livewhale_geo',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => [
            [
                [
                    'field' => 'field_livewhale_geo_valid'.$suffix,
                    'operator' => '==',
                    'value' => 'true',
                ],
            ],
        ],
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'choices' => [
            'include' => 'Include',
            'exclude' => 'Exclude',
        ],
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ],
    [
        'key' => 'field_livewhale_geo_region'.$suffix,
        'label' => 'Regions',
        'name' => 'livewhale_geo_region',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'choices' => [
            'central' => 'Central',
            'northeast' => 'Northeast',
            'northwest' => 'Northwest',
            'southeast' => 'Southeast',
            'southwest' => 'Southwest',
        ],
        'default_value' => [
        ],
        'allow_null' => 0,
        'multiple' => 1,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'allow_custom' => 0,
        'placeholder' => '',
        'search_placeholder' => '',
    ],
];
