<?php
/*
 *
 * Module Layout Fields
 * 
 */
return array (
    array(
        'acfe_flexible_advanced' => 1,
		'acfe_flexible_stylised_button' => 0,
		'acfe_flexible_hide_empty_message' => 0,
		'acfe_flexible_empty_message' => '',
		'acfe_flexible_disable_ajax_title' => 1,
		'acfe_flexible_layouts_thumbnails' => 0,
		'acfe_flexible_layouts_settings' => 0,
		'acfe_flexible_layouts_ajax' => 1,
		'acfe_flexible_layouts_templates' => 0,
		'acfe_flexible_layouts_previews' => 0,
		'acfe_flexible_layouts_placeholder' => 0,
		'acfe_flexible_title_edition' => 1,
		'acfe_flexible_clone' => 1,
		'acfe_flexible_copy_paste' => 0,
		'acfe_flexible_close_button' => 0,
		'acfe_flexible_remove_add_button' => 0,
		'acfe_flexible_remove_delete_button' => 0,
		'acfe_flexible_lock' => 0,
		'acfe_flexible_modal_edition' => 0,
		'acfe_flexible_modal' => array(
			'acfe_flexible_modal_enabled' => '0',
		),
		'acfe_flexible_layouts_state' => '',
		'acfe_flexible_layouts_remove_collapse' => 0,
        'key' => 'field_uamswp_modules',
        'label' => 'Modules',
        'name' => 'uamswp_modules',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_permissions' => '',
        'layouts' => array(
            // 'layout_5d126463e2192' => array(
            //     'key' => 'layout_5d126463e2192',
            //     'name' => 'modules_heading',
            //     'label' => 'Heading',
            //     'display' => 'block',
            //     'sub_fields' => $heading,
            //     'min' => '',
            //     'max' => '',
            // ),
            'layout_content' => array(
                'key' => 'layout_content',
                'name' => 'modules_uams_content',
                'label' => 'Content',
                'display' => 'block',
                'sub_fields' => $content,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_action_bar' => array(
                'key' => 'layout_modules_action_bar',
                'name' => 'modules_action_bar',
                'label' => 'Action Bar',
                'display' => 'block',
                'sub_fields' => $action_bar,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_call_out' => array(
                'key' => 'layout_modules_call_out',
                'name' => 'modules_call_out',
                'label' => 'Call-Out',
                'display' => 'block',
                'sub_fields' => $call_out,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_cta' => array(
                'key' => 'layout_modules_cta',
                'name' => 'modules_cta',
                'label' => 'Call-to-Action (CTA) Bar',
                'display' => 'block',
                'sub_fields' => $cta,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_hero' => array(
                'key' => 'layout_modules_hero',
                'name' => 'modules_hero',
                'label' => 'Hero',
                'display' => 'block',
                'sub_fields' => $hero,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_link_list' => array(
                'key' => 'layout_modules_link_list',
                'name' => 'modules_link_list',
                'label' => 'Link List',
                'display' => 'block',
                'sub_fields' => $link_list,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_news_grid' => array(
                'key' => 'layout_modules_news_grid',
                'name' => 'modules_news_grid',
                'label' => 'UAMS News',
                'display' => 'block',
                'sub_fields' => $news,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_text_overlay' => array(
                'key' => 'layout_modules_text_overlay',
                'name' => 'modules_text_overlay',
                'label' => 'Text & Image Overlay',
                'display' => 'block',
                'sub_fields' => $overlay,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_post_tile' => array(
                'key' => 'layout_modules_post_tile',
                'name' => 'modules_post_tile',
                'label' => 'Post Category Tile (Single)',
                'display' => 'block',
                'sub_fields' => $post_tile,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_post_tiles' => array(
                'key' => 'layout_modules_post_tiles',
                'name' => 'modules_post_tiles',
                'label' => 'Post Category Tile (Double)',
                'display' => 'block',
                'sub_fields' => $post_tiles,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_image_side' => array(
                'key' => 'layout_modules_image_side',
                'name' => 'modules_image_side',
                'label' => 'Side-by-side Image & Text',
                'display' => 'block',
                'sub_fields' => $side_by_side,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_text_stacked' => array(
                'key' => 'layout_modules_text_stacked',
                'name' => 'modules_text_stacked',
                'label' => 'Stacked Image & Text',
                'display' => 'block',
                'sub_fields' => $stacked,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_uams_livewhale' => array(
                'key' => 'layout_modules_uams_livewhale',
                'name' => 'modules_uams_livewhale',
                'label' => 'Livewhale Calendar',
                'display' => 'block',
                'sub_fields' => $livewhale,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_uams_gallery' => array(
                'key' => 'layout_modules_uams_gallery',
                'name' => 'modules_uams_gallery',
                'label' => 'Gallery',
                'display' => 'block',
                'sub_fields' => $gallery,
                'min' => '',
                'max' => '',
            ),
        ),
        'button_label' => 'Add Module',
        'min' => '',
        'max' => '',
    ),
);