<?php
/*
 *
 * Module Layout Fields
 * 
 */
return array (
    array(
        'key' => 'field_uamswp_modules',
        'label' => 'Modules',
        'name' => 'uamswp_modules',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layouts' => array(
            // 'layout_5d126463e2192' => array(
            //     'key' => 'layout_5d126463e2192',
            //     'name' => 'modules_heading',
            //     'label' => 'Heading',
            //     'display' => 'block',
            //     'sub_fields' => $heading,
            //     'min' => '',
            //     'max' => '',
            // ),
            'layout_modules_action_bar' => array(
                'key' => 'layout_modules_action_bar',
                'name' => 'modules_action_bar',
                'label' => 'Action Bar',
                'display' => 'block',
                'sub_fields' => $action_bar,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_call_out' => array(
                'key' => 'layout_modules_call_out',
                'name' => 'modules_call_out',
                'label' => 'Call-Out',
                'display' => 'block',
                'sub_fields' => $call_out,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_cta' => array(
                'key' => 'layout_modules_cta',
                'name' => 'modules_cta',
                'label' => 'Call-to-Action (CTA) Bar',
                'display' => 'block',
                'sub_fields' => $cta,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_hero' => array(
                'key' => 'layout_modules_hero',
                'name' => 'modules_hero',
                'label' => 'Hero',
                'display' => 'block',
                'sub_fields' => $hero,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_text_overlay' => array(
                'key' => 'layout_modules_text_overlay',
                'name' => 'modules_text_overlay',
                'label' => 'Text & Image Overlay',
                'display' => 'block',
                'sub_fields' => $overlay,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_post_tile' => array(
                'key' => 'layout_modules_post_tile',
                'name' => 'modules_post_tile',
                'label' => 'Post Category Tile (Single)',
                'display' => 'block',
                'sub_fields' => $post_tile,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_post_tiles' => array(
                'key' => 'layout_modules_post_tiles',
                'name' => 'modules_post_tiles',
                'label' => 'Post Category Tile (Double)',
                'display' => 'block',
                'sub_fields' => $post_tiles,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_image_side' => array(
                'key' => 'layout_modules_image_side',
                'name' => 'modules_image_side',
                'label' => 'Side-by-side Image & Text',
                'display' => 'block',
                'sub_fields' => $side_by_side,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_text_stacked' => array(
                'key' => 'layout_modules_text_stacked',
                'name' => 'modules_text_stacked',
                'label' => 'Stacked Image & Text',
                'display' => 'block',
                'sub_fields' => $stacked,
                'min' => '',
                'max' => '',
            ),
            'layout_modules_news_grid' => array(
                'key' => 'layout_modules_news_grid',
                'name' => 'modules_news_grid',
                'label' => 'News Grid',
                'display' => 'block',
                'sub_fields' => $newsgrid,
                'min' => '',
                'max' => '',
            ),
        ),
        'button_label' => 'Add Module',
        'min' => '',
        'max' => '',
    ),
);