<?php
/*
 *
 * Module Layout Fields
 * 
 */
return array (
    array(
        'key' => 'field_uamswp_modules',
        'label' => 'Modules',
        'name' => 'uamswp_modules',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'acfe_flexible_advanced' => 1,
		'acfe_flexible_stylised_button' => 1,
		'acfe_flexible_hide_empty_message' => 0,
		'acfe_flexible_empty_message' => '',
		'acfe_flexible_disable_ajax_title' => 1,
		'acfe_flexible_layouts_thumbnails' => 1,
		'acfe_flexible_layouts_settings' => 1,
		'acfe_flexible_layouts_ajax' => 1,
		'acfe_flexible_layouts_templates' => 1,
		'acfe_flexible_layouts_previews' => 1,
		'acfe_flexible_layouts_placeholder' => '',
		'acfe_flexible_title_edition' => 1,
		'acfe_flexible_clone' => 1,
		'acfe_flexible_copy_paste' => 0,
		'acfe_flexible_close_button' => 0,
		'acfe_flexible_remove_add_button' => 0,
		'acfe_flexible_remove_delete_button' => 0,
		'acfe_flexible_lock' => 0,
		'acfe_flexible_modal_edition' => 0,
		'acfe_flexible_modal' => array(
            'acfe_flexible_modal_enabled' => '1',
            'acfe_flexible_modal_title' => '',
            'acfe_flexible_modal_size' => 'large',
            'acfe_flexible_modal_col' => '4',
            'acfe_flexible_modal_categories' => '1',
        ),
		'acfe_flexible_layouts_state' => '',
		'acfe_flexible_layouts_remove_collapse' => 0,
        'hide_field' => '',
		'hide_label' => 'admin',
		'hide_instructions' => 'all',
		'hide_required' => '',
        'acfe_permissions' => '',
        'layouts' => array(
            // 'layout_5d126463e2192' => array(
            //     'key' => 'layout_5d126463e2192',
            //     'name' => 'modules_heading',
            //     'label' => 'Heading',
            //     'display' => 'block',
            //     'sub_fields' => $heading,
            //     'min' => '',
            //     'max' => '',
            // ),
            'layout_content' => array(
                'key' => 'layout_content',
                'name' => 'modules_uams_content',
                'label' => 'Content',
                'display' => 'block',
                'sub_fields' => $content,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Text',
                ),
                'acfe_flexible_render_template' => 'blocks/content.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Content_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_action_bar' => array(
                'key' => 'layout_modules_action_bar',
                'name' => 'modules_action_bar',
                'label' => 'Action Bar',
                'display' => 'block',
                'sub_fields' => $action_bar,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Text',
                    1 => 'Navigation'
                ),
                'acfe_flexible_render_template' => 'blocks/action-bar.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Action_Bar_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_call_out' => array(
                'key' => 'layout_modules_call_out',
                'name' => 'modules_call_out',
                'label' => 'Call-Out',
                'display' => 'block',
                'sub_fields' => $call_out,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Text',
                ),
                'acfe_flexible_render_template' => 'blocks/call-out.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Call-Out_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_cta' => array(
                'key' => 'layout_modules_cta',
                'name' => 'modules_cta',
                'label' => 'Call-to-Action (CTA) Bar',
                'display' => 'block',
                'sub_fields' => $cta,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Text',
                ),
                'acfe_flexible_render_template' => 'blocks/cta.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Call-to-Action__CTA__Bar_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_hero' => array(
                'key' => 'layout_modules_hero',
                'name' => 'modules_hero',
                'label' => 'Hero',
                'display' => 'block',
                'sub_fields' => $hero,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Image',
                    1 => 'Text',
                ),
                'acfe_flexible_render_template' => 'blocks/hero.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Hero_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_link_list' => array(
                'key' => 'layout_modules_link_list',
                'name' => 'modules_link_list',
                'label' => 'Link List',
                'display' => 'block',
                'sub_fields' => $link_list,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Text',
                ),
                'acfe_flexible_render_template' => 'blocks/link-list.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Link_List_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_news_grid' => array(
                'key' => 'layout_modules_news_grid',
                'name' => 'modules_news_grid',
                'label' => 'UAMS News',
                'display' => 'block',
                'sub_fields' => $news,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'News',
                ),
                'acfe_flexible_render_template' => 'blocks/news.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_News_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_text_overlay' => array(
                'key' => 'layout_modules_text_overlay',
                'name' => 'modules_text_overlay',
                'label' => 'Text & Image Overlay',
                'display' => 'block',
                'sub_fields' => $overlay,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Image',
                ),
                'acfe_flexible_render_template' => 'blocks/overlay.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Text___Image_Overlay_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_post_tile' => array(
                'key' => 'layout_modules_post_tile',
                'name' => 'modules_post_tile',
                'label' => 'Post Category Tile (Single)',
                'display' => 'block',
                'sub_fields' => $post_tile,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'News',
                ),
                'acfe_flexible_render_template' => 'blocks/post-category-tile.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Content_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_post_tiles' => array(
                'key' => 'layout_modules_post_tiles',
                'name' => 'modules_post_tiles',
                'label' => 'Post Category Tile (Double)',
                'display' => 'block',
                'sub_fields' => $post_tiles,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'News',
                ),
                'acfe_flexible_render_template' => 'blocks/post-category-tiles.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Content_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_image_side' => array(
                'key' => 'layout_modules_image_side',
                'name' => 'modules_image_side',
                'label' => 'Side-by-side Image & Text',
                'display' => 'block',
                'sub_fields' => $side_by_side,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Image',
                ),
                'acfe_flexible_render_template' => 'blocks/image-side-by-side.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Side-by-Side_Image___Text_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_text_stacked' => array(
                'key' => 'layout_modules_text_stacked',
                'name' => 'modules_text_stacked',
                'label' => 'Stacked Image & Text',
                'display' => 'block',
                'sub_fields' => $stacked,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Image',
                ),
                'acfe_flexible_render_template' => 'blocks/stacked.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Stacked_Image___Text_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_uams_livewhale' => array(
                'key' => 'layout_modules_uams_livewhale',
                'name' => 'modules_uams_livewhale',
                'label' => 'Livewhale Calendar',
                'display' => 'block',
                'sub_fields' => $livewhale,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Calendar',
                ),
                'acfe_flexible_render_template' => 'blocks/livewhale.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Calendar_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_uams_gallery' => array(
                'key' => 'layout_modules_uams_gallery',
                'name' => 'modules_uams_gallery',
                'label' => 'Gallery',
                'display' => 'block',
                'sub_fields' => $gallery,
                'min' => '',
                'max' => '',
                'acfe_flexible_category' => array(
                    0 => 'Image',
                ),
                'acfe_flexible_render_template' => 'blocks/gallery.php',
                'acfe_flexible_render_style' => '',
                'acfe_flexible_render_script' => '',
                'acfe_flexible_settings' => '',
                'acfe_flexible_settings_size' => 'medium',
                'acfe_flexible_thumbnail' => '/wp-content/themes/uams-2020/assets/png/UAMS_Gallery_Block.png',
                'acfe_flexible_modal_edit_size' => false,
                'acfe_layout_col' => 'auto',
                'acfe_layout_allowed_col' => false,
            ),
            'layout_modules_uams_section' => array(
                'key' => 'layout_modules_uams_section',
                'name' => 'modules_uams_section',
                'label' => 'Section',
                'display' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_modules_uams_section_heading',
                        'label' => 'Heading',
                        'name' => 'modules_uams_section_heading',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_modules_uams_section_hide_heading',
                        'label' => 'Hide Heading',
                        'name' => 'modules_uams_section_hide_heading',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_modules_uams_section_background_color',
                        'label' => 'Background Color',
                        'name' => 'modules_uams_section_background_color',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'bg-auto' => 'Auto',
                            'bg-white' => 'White',
                            'bg-gray' => 'Gray',
                            'bg-red' => 'Red',
                            'bg-black' => 'Black',
                            'bg-blue' => 'Blue',
                            'bg-green' => 'Green',
                            'bg-teal' => 'Teal',
                            'bg-eggplant' => 'Eggplant',
                            'bg-orange' => 'Orange',
                        ),
                        'default_value' => 'bg-auto',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_modules_uams_section_flexible_layout',
                        'label' => 'Flexible Layout',
                        'name' => 'modules_uams_section_flexible_layout',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_flexible_advanced' => 1,
                        'acfe_flexible_stylised_button' => 1,
                        'acfe_flexible_layouts_templates' => 0,
                        'acfe_flexible_layouts_placeholder' => 0,
                        'acfe_flexible_layouts_thumbnails' => 0,
                        'acfe_flexible_layouts_settings' => 0,
                        'acfe_flexible_async' => array(
                        ),
                        'acfe_flexible_add_actions' => array(
                            0 => 'title',
                        ),
                        'acfe_flexible_remove_button' => array(
                        ),
                        'acfe_flexible_modal_edit' => array(
                            'acfe_flexible_modal_edit_enabled' => '1',
                            'acfe_flexible_modal_edit_size' => 'xlarge',
                        ),
                        'acfe_flexible_modal' => array(
                            'acfe_flexible_modal_enabled' => '0',
                            'acfe_flexible_modal_title' => false,
                            'acfe_flexible_modal_size' => 'full',
                            'acfe_flexible_modal_col' => '4',
                            'acfe_flexible_modal_categories' => false,
                        ),
                        'layouts' => array(
                            'layout_modules_uams_section_wysiwyg' => array(
                                'key' => 'layout_modules_uams_section_wysiwyg',
                                'name' => 'uams_section_wysiwyg',
                                'label' => 'HTML',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_section_wysiwyg_html',
                                        'label' => 'Content / HTML',
                                        'name' => 'section_wysiwyg_html',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 1,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                                'acfe_flexible_render_template' => false,
                                'acfe_flexible_render_style' => false,
                                'acfe_flexible_render_script' => false,
                                'acfe_flexible_thumbnail' => false,
                                'acfe_flexible_settings' => false,
                                'acfe_flexible_settings_size' => 'medium',
                                'acfe_flexible_modal_edit_size' => false,
                                'acfe_flexible_category' => false,
                            ),
                            'layout_modules_uams_section_youtube' => array(
                                'key' => 'layout_modules_uams_section_youtube',
                                'name' => 'modules_uams_section_youtube',
                                'label' => 'Embed / YouTube',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_section_youtube_width',
                                        'label' => 'Width',
                                        'name' => 'section_youtube_width',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'aligncenter' => 'Center (Content Width)',
                                            'alignwide' => 'Wide',
                                            'alignfull' => 'Full',
                                        ),
                                        'default_value' => 'aligncenter',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'value',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_section_youtube_url',
                                        'label' => 'Embed URL / YouTube URL',
                                        'name' => 'section_youtube_url',
                                        'type' => 'url',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                                'acfe_flexible_render_template' => false,
                                'acfe_flexible_render_style' => false,
                                'acfe_flexible_render_script' => false,
                                'acfe_flexible_thumbnail' => false,
                                'acfe_flexible_settings' => false,
                                'acfe_flexible_settings_size' => 'medium',
                                'acfe_flexible_modal_edit_size' => false,
                                'acfe_flexible_category' => false,
                            ),
                        ),
                        'button_label' => 'Add Row',
                        'min' => '',
                        'max' => '',
                        'acfe_flexible_hide_empty_message' => false,
                        'acfe_flexible_empty_message' => '',
                        'acfe_flexible_layouts_previews' => false,
                        'acfe_flexible_layouts_state' => false,
                    ),
                ),
                'min' => '',
                'max' => '',
            ),
        ),
        'button_label' => 'Add Module',
        'min' => '',
        'max' => '',
    ),
);