<?php

declare(strict_types=1);

/*
 *
 * News Grid  
 * 
 */
if (class_exists('UAMS_Syndicate_News_Base')) {
    return [
		[
			'key' => 'field_news_intro'. $suffix,
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '<h2>UAMS News Block</h2>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		],
		[
			'key' => 'field_news_base'. $suffix,
			'label' => '<i class="dashicons dashicons-feedback"></i> Base',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'open' => 1,
			'multi_expand' => 0,
			'endpoint' => 0,
		],
		[
			'key' => 'field_news_format'. $suffix,
			'label' => 'Format',
			'name' => 'news_format',
			'type' => 'select',
			'instructions' => 'Select format (number of articles)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'headlines' => 'Headlines',
				'excerpts' => 'Excerpts',
				'cards' => 'Cards (4)',
				'full' => 'Full (1)',
				'grid' => 'Grid (3)',
				'side' => 'Side-by-Side Image & Text (1)',
				// 'json' => 'JSON',
			],
			'default_value' => [
				0 => 'grid',
			],
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		],
		[
			'key' => 'field_news_title'. $suffix,
			'label' => 'Section Title',
			'name' => 'news_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'side',
					],
				],
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 'News & Announcements',
			'placeholder' => 'News & Announcements',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_news_hide_title'. $suffix,
			'label' => 'Hide Section Title',
			'name' => 'news_hide_title',
			'type' => 'true_false',
			'instructions' => 'The heading is necessary for page hierarchy. But it can be hidden from all but screen readers and search engines. This is not recommended in most cases.',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'side',
					],
				],
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_news_category'. $suffix,
			'label' => 'Category',
			'name' => 'news_category',
			'type' => 'text',
			'instructions' => 'Please enter the filter / category slug',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_news_count'. $suffix,
			'label' => 'Count',
			'name' => 'news_count',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'headlines',
					],
				],
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'excerpts',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 9,
			'step' => '',
		],
		[
			'key' => 'field_news_offset'. $suffix,
			'label' => 'Offset',
			'name' => 'news_offset',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 8,
			'step' => '',
		],
		[
			'key' => 'field_news_background_color'. $suffix,
			'label' => 'Background Color',
			'name' => 'news_background_color',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'bg-auto' => 'Auto',
				'bg-white' => 'White',
				'bg-gray' => 'Gray',
			],
			'allow_null' => 0,
			'default_value' => [
				0 => 'bg-auto',
			],
			'layout' => 'horizontal',
			'return_format' => 'value',
		],
		[
			'key' => 'field_news_hide_img'. $suffix,
			'label' => 'Hide Images',
			'name' => 'news_hide_img',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'side',
					],
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_news_hide_author'. $suffix,
			'label' => 'Hide Author',
			'name' => 'news_hide_author',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'side',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_news_hide_date'. $suffix,
			'label' => 'Hide Date',
			'name' => 'news_hide_date',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'side',
					],
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '!=',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_news_include_link'. $suffix,
			'label' => 'Include link to category',
			'name' => 'news_include_link',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'grid',
					],
				],
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'cards',
					],
				],
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'side',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'1' => 'Yes',
				'0' => 'No',
			],
			'allow_null' => 0,
			'default_value' => '1',
			'layout' => 'horizontal',
			'return_format' => 'value',
		],
		[
			'key' => 'field_news_position'. $suffix,
			'label' => 'Image & Text Position',
			'name' => 'news_position',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'side',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'left' => 'Image on Left, Text on Right',
            	'right' => 'Image on Right, Text on Left',
			],
			'allow_null' => 0,
			'default_value' => 'left',
			'layout' => 'horizontal',
			'return_format' => 'value',
		],
		[
			'key' => 'field_news_article_id'. $suffix,
			'label' => 'Article ID',
			'name' => 'news_article_id',
			'type' => 'text',
			'instructions' => 'Enter the Article ID from news.uams.edu',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_format'. $suffix,
						'operator' => '==',
						'value' => 'full',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_news_advanced'. $suffix,
			'label' => '<i class="dashicons dashicons-admin-settings"></i> Advanced',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		],
		[
			'key' => 'field_news_local'. $suffix,
			'label' => 'Include Local',
			'name' => 'news_local',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		],
		[
			'key' => 'field_news_advanced_cat'. $suffix,
			'label' => 'Advanced Category',
			'name' => 'news_advanced_cat',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_news_geo_valid'. $suffix,
			'label' => 'GeoTargetingWP Installed?',
			'name' => 'geo_valid',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => 'hidden',
				'id' => '',
			],
			'acfe_permissions' => '',
			'choices' => [
				'false' => 'False',
				'true' => 'True',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'false',
			'layout' => 'horizontal',
			'return_format' => 'value',
		],
		[
			'key' => 'field_news_regions'. $suffix,
			'label' => '<i class="dashicons dashicons-location-alt"></i> Region Filter',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_geo_valid'. $suffix,
						'operator' => '==',
						'value' => 'true',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		],
		[
			'key' => 'field_news_geo'. $suffix,
			'label' => 'Regions',
			'name' => 'news_geo',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_news_geo_valid'. $suffix,
						'operator' => '==',
						'value' => 'true',
					],
				],
			],
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'acfe_permissions' => '',
			'choices' => [
				'include' => 'Include',
				'exclude' => 'Exclude',
			],
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value'
		],
		[
			'key' => 'field_news_geo_region'. $suffix,
			'label' => 'Regions',
			'name' => 'news_geo_region',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'acfe_permissions' => '',
			'choices' => [
				'central' => 'Central',
				'northeast' => 'Northeast',
				'northwest' => 'Northwest',
				'southeast' => 'Southeast',
				'southwest' => 'Southwest',
			],
			'default_value' => [
			],
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'allow_custom' => 0,
			'placeholder' => '',
			'search_placeholder' => '',
		],
    ];
}

return [
    [
        'key' => 'field_news_not_available'. $suffix,
			'label' => 'Not Available',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'message' => 'This module is not available, please activate News Syndication plugin.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
    ],
];
