<?php
/*
 *
 * Post Category Tiles (Double) Block Fields
 * 
 */
return array(
    array(
        'key' => 'field_post_tiles_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>News Category Tiles</h2>
            <p>This block is only intended to be used on the sidebar layout.</p>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_post_tiles_heading'. $suffix,
        'label' => 'Module Heading',
        'name' => 'post_tiles_heading',
        'type' => 'text',
        'instructions' => 'Even if this heading is hidden, it is necessary for accessibility.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_post_tiles_hide_heading'. $suffix,
        'label' => 'Hide the Module Heading?',
        'name' => 'post_tiles_hide_heading',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_post_tiles_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'post_tiles_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_post_tiles_section'. $suffix,
        'label' => 'Items',
        'name' => 'post_tiles_section',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => '',
        'min' => 2,
        'max' => 2,
        'layout' => 'block',
        'button_label' => 'Add item',
        'sub_fields' => array(
            array(
                'key' => 'field_post_tiles_section_category'. $suffix,
                'label' => 'Post Category',
                'name' => 'post_tiles_section_category',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'category',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'object',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_post_tiles_section_post_button_text'. $suffix,
                'label' => 'Post\'s Button Text',
                'name' => 'post_tiles_section_post_button_text',
                'type' => 'text',
                'instructions' => 'Text for the button linking to the individual post.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Read the Story',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_post_tiles_section_category_button_text'. $suffix,
                'label' => 'Category Link\'s Button Text',
                'name' => 'post_tiles_section_category_button_text',
                'type' => 'text',
                'instructions' => 'Text for the button linking to the full category',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'View [Category Name] Archive',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
    ),
);