<?php
/*
 *
 * Post Category Tile (Single) Block Fields
 * 
 */
return array(
    array(
        'key' => 'field_post_tile_intro'. $suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>UAMS Post Category Tile (Single) Block</h2>
        <p>This block is only intended to be used on the sidebar layout.</p>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_post_tile_heading'. $suffix,
        'label' => 'Heading',
        'name' => 'post_tile_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_post_tile_hide_heading'. $suffix,
        'label' => 'Hide Heading?',
        'name' => 'post_tile_hide_heading',
        'type' => 'true_false',
        'instructions' => 'The heading is necessary for page hierarchy. But it can be hidden from all but screen readers and search engines. This is not recommended in most cases.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_post_tile_category'. $suffix,
        'label' => 'Post Category',
        'name' => 'post_tile_category',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'taxonomy' => 'category',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'object',
        'multiple' => 0,
    ),
    array(
        'key' => 'field_post_tile_post_button_text'. $suffix,
        'label' => 'Post Link\'s Button Text',
        'name' => 'post_tile_post_button_text',
        'type' => 'text',
        'instructions' => 'Text for the button linking to the individual post',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => 'Read the Story',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_post_tile_category_button_text'. $suffix,
        'label' => 'Category Link\'s Button Text',
        'name' => 'post_tile_category_button_text',
        'type' => 'text',
        'instructions' => 'Text for the button linking to the full category',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => 'View [Category Name] Archive',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_post_tile_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'post_tile_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
);