<?php

declare(strict_types=1);

/*
 *
 * Post Category Tile (Single) Block Fields
 *
 */
return [
    [
        'key' => 'field_post_tile_intro'.$suffix,
        'label' => '',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'message' => '<h2>UAMS Post Category Tile (Single) Block</h2>
        <p>This block is only intended to be used on the sidebar layout.</p>',
        'new_lines' => '',
        'esc_html' => 0,
    ],
    [
        'key' => 'field_post_tile_heading'.$suffix,
        'label' => 'Heading',
        'name' => 'post_tile_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_post_tile_hide_heading'.$suffix,
        'label' => 'Hide Heading?',
        'name' => 'post_tile_hide_heading',
        'type' => 'true_false',
        'instructions' => 'The heading is necessary for page hierarchy. But it can be hidden from all but screen readers and search engines. This is <strong>strongly</strong> not recommended in most cases, as the visible heading provides a jumping-in point for users as they scan your page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ],
    [
        'key' => 'field_post_tile_category'.$suffix,
        'label' => 'Post Category',
        'name' => 'post_tile_category',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'taxonomy' => 'category',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'object',
        'multiple' => 0,
    ],
    [
        'key' => 'field_post_tile_post_button_text'.$suffix,
        'label' => "Post Link's Button Text",
        'name' => 'post_tile_post_button_text',
        'type' => 'text',
        'instructions' => 'Text for the button linking to the individual post',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => 'Read the Story',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_post_tile_category_button_text'.$suffix,
        'label' => "Category Link's Button Text",
        'name' => 'post_tile_category_button_text',
        'type' => 'text',
        'instructions' => 'Text for the button linking to the full category',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => 'View [Category Name] Archive',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_post_tile_background_color'.$suffix,
        'label' => 'Background Color',
        'name' => 'post_tile_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'choices' => [
            'bg-auto' => 'Auto',
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
        ],
        'default_value' => [
            0 => 'bg-auto',
        ],
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ],
    [
        'key' => 'field_post_tile_geo_valid'.$suffix,
        'label' => 'GeoTargetingWP Installed?',
        'name' => 'geo_valid',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => 'hidden',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'choices' => [
            'false' => 'False',
            'true' => 'True',
        ],
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => 'false',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ],
    [
        'key' => 'field_post_tile_regions'.$suffix,
        'label' => '<i class="dashicons dashicons-location-alt"></i> Region Filter',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => [
            [
                [
                    'field' => 'field_post_tile_geo_valid'.$suffix,
                    'operator' => '==',
                    'value' => 'true',
                ],
            ],
        ],
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ],
    [
        'key' => 'field_post_tile_geo'.$suffix,
        'label' => 'Regions',
        'name' => 'post_tile_geo',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => [
            [
                [
                    'field' => 'field_post_tile_geo_valid'.$suffix,
                    'operator' => '==',
                    'value' => 'true',
                ],
            ],
        ],
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'choices' => [
            'include' => 'Include',
            'exclude' => 'Exclude',
        ],
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ],
    [
        'key' => 'field_post_tile_geo_region'.$suffix,
        'label' => 'Regions',
        'name' => 'post_tile_geo_region',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'acfe_permissions' => '',
        'choices' => [
            'central' => 'Central',
            'northeast' => 'Northeast',
            'northwest' => 'Northwest',
            'southeast' => 'Southeast',
            'southwest' => 'Southwest',
        ],
        'default_value' => [
        ],
        'allow_null' => 0,
        'multiple' => 1,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'allow_custom' => 0,
        'placeholder' => '',
        'search_placeholder' => '',
    ],
];
