<?php
/*
 *
 * Stacked Image & Text Block Fields
 * 
 */
return array(
    array(
        'key' => 'field_stacked_intro'. $suffix,
        'label' => '',
        'name' => 'stacked_intro',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '<h2>Stacked Image &amp; Text</h2>',
        'new_lines' => '',
        'esc_html' => 0,
    ),
    array(
        'key' => 'field_stacked_heading'. $suffix,
        'label' => 'Module Heading',
        'name' => 'stacked_heading',
        'type' => 'text',
        'instructions' => 'Even if this heading is hidden, it is necessary for accessibility.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_stacked_hide_heading'. $suffix,
        'label' => 'Hide the Module Heading?',
        'name' => 'stacked_hide_heading',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
    ),
    array(
        'key' => 'field_stacked_background_color'. $suffix,
        'label' => 'Background Color',
        'name' => 'stacked_background_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-white' => 'White',
            'bg-gray' => 'Gray',
        ),
        'default_value' => array(
            0 => 'bg-white',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_stacked_section'. $suffix,
        'label' => 'Items',
        'name' => 'stacked_section',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => '',
        'min' => 4,
        'max' => 4,
        'layout' => 'block',
        'button_label' => '',
        'sub_fields' => array(
            array(
                'key' => 'stacked_section_intro'. $suffix,
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h3>Item Options</h3>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_stacked_section_heading'. $suffix,
                'label' => 'Heading',
                'name' => 'stacked_section_heading',
                'type' => 'text',
                'instructions' => '78 character limit.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 78,
            ),
            array(
                'key' => 'field_stacked_section_body'. $suffix,
                'label' => 'Body',
                'name' => 'stacked_section_body',
                'type' => 'textarea',
                'instructions' => '179 character limit.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '179',
                'rows' => 3,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_stacked_section_image'. $suffix,
                'label' => 'Image',
                'name' => 'stacked_section_image',
                'type' => 'image',
                'instructions' => 'Recommended image dimensions: 910x512. Minimum image dimensions: 455x256. The image will automatically be cropped to a 16:9 aspect ratio.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => 455,
                'min_height' => 256,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_stacked_section_alt_override'. $suffix,
                'label' => 'Image Alt Text Override',
                'name' => 'stacked_section_alt_override',
                'type' => 'text',
                'instructions' => 'Alt text (alternative text) refers to invisible description of images which are read aloud to blind users on a screen reader. If you want to define alt text that is different from the alt text defined for this image in the media library, you can do so here.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 125,
            ),
            array(
                'key' => 'field_stacked_section_button_text'. $suffix,
                'label' => 'Button Text',
                'name' => 'stacked_section_button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_stacked_section_button_url'. $suffix,
                'label' => 'Button URL',
                'name' => 'stacked_section_button_url',
                'type' => 'url',
                'instructions' => 'Include http:// or https://.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_stacked_section_button_target'. $suffix,
                'label' => 'Open in New Window?',
                'name' => 'stacked_section_button_target',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_stacked_section_button_description'. $suffix,
                'label' => 'Button Link Description',
                'name' => 'stacked_section_button_description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
    ),
);