<?php

/*
 *
 * Custom ACF Blocks
 * 
 */

add_action('acf/init', 'uams_register_blocks');
function uams_register_blocks() {

    // check function exists.
    if( function_exists('acf_register_block_type') ) {

        // register a hero block.
        acf_register_block_type(array(
            'name'              => 'hero',
            'title'             => __('UAMS Hero'),
            'description'       => __('UAMS Hero / Slideshow.'),
            'category'          => 'common',
            'icon'              => 'images-alt2',
            'keywords'          => array('uams', 'slides', 'slideshow', 'hero'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/hero.php',
        ));
        acf_register_block_type(array(
            'name'              => 'image-side',
            'title'             => __('UAMS Side-by-Side Image & Text'),
            'description'       => __('Image on one side, text on the other side.'),
            'category'          => 'common',
            'icon'              => 'id',
            'keywords'          => array('uams', 'text', 'image', 'side'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/image-side-by-side.php',
        ));
        acf_register_block_type(array(
            'name'              => 'text-stacked',
            'title'             => __('UAMS Stacked Image & Text'),
            'description'       => __('Stacked Image & Text'),
            'category'          => 'common',
            'icon'              => 'screenoptions',
            'keywords'          => array('uams', 'text', 'image', 'stack', 'stacked'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/stacked.php',
        ));
        acf_register_block_type(array(
            'name'              => 'text-overlay',
            'title'             => __('UAMS Text & Image Overlay'),
            'description'       => __('Text and a button on top of an image.'),
            'category'          => 'common',
            'icon'              => 'format-image',
            'keywords'          => array('uams', 'text', 'image', 'overlay'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/overlay.php',
        ));
        acf_register_block_type(array(
            'name'              => 'cta',
            'title'             => __('UAMS CTA Bar'),
            'description'       => __('Call-to-Action (CTA) Bar.'),
            'category'          => 'common',
            'icon'              => 'format-status',
            'keywords'          => array('uams', 'cta', 'call-to-action', 'call to action', 'button'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/cta.php',
        ));
        acf_register_block_type(array(
            'name'              => 'call-out',
            'title'             => __('UAMS Call-Out'),
            'description'       => __('Call-Out.'),
            'category'          => 'common',
            'icon'              => 'megaphone',
            'keywords'          => array('uams', 'callout', 'call-out', 'text'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/call-out.php',
        ));
        acf_register_block_type(array(
            'name'              => 'action-bar',
            'title'             => __('UAMS Action Bar'),
            'description'       => __('Action Bar.'),
            'category'          => 'common',
            'icon'              => 'admin-links',
            'keywords'          => array('uams', 'action bar', 'links'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/action-bar.php',
        ));
        // acf_register_block_type(array(
        //     'name'              => 'block',
        //     'title'             => __('UAMS Block'),
        //     'description'       => __('A custom hero block.'),
        //     'category'          => 'common',
        //     'icon'              => '',
        //     'keywords'          => array('uams', 'block'),
        //     'mode'              => 'auto',
        //     'align'             => 'full',
        //     'render_template'   => 'blocks/block.php',
		// ));
    }
}

if( function_exists('acf_add_local_field_group') ):

    // Add local field group for UAMS Side-by-Side Image & Text Block
    acf_add_local_field_group(array(
        'key' => 'group_5cefe13df1b97',
        'title' => 'Block: Side-by-Side Image & Text',
        'fields' => array(
            array(
                'key' => 'field_side_image_intro-message',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Side-by-Side Image & Text</h2>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_side_text-layout',
                'label' => 'Choose Text Layout',
                'name' => 'side_text-layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'body-only' => 'Body only',
                    'link-list' => 'Body and Link List',
                ),
                'default_value' => array(
                    0 => 'body-only',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_side_heading',
                'label' => 'Heading',
                'name' => 'side_heading',
                'type' => 'text',
                'instructions' => '50 character limit.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 50,
            ),
            array(
                'key' => 'field_side_layout-body-only_body',
                'label' => 'Body',
                'name' => 'side_layout-body-only_body',
                'type' => 'textarea',
                'instructions' => '449 character limit.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_side_text-layout',
                            'operator' => '==',
                            'value' => 'body-only',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => 449,
                'rows' => 6,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_side_layout-link-list_body',
                'label' => 'Body',
                'name' => 'side_layout-link-list_body',
                'type' => 'textarea',
                'instructions' => '173 character limit.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_side_text-layout',
                            'operator' => '==',
                            'value' => 'link-list',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => 173,
                'rows' => 3,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_side_link-list',
                'label' => 'Link List',
                'name' => 'side_link-list',
                'type' => 'repeater',
                'instructions' => 'You may add up to six links. However, if you add a sixth link, the option for adding "and more" in the sixth position will be disabled.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_side_text-layout',
                            'operator' => '==',
                            'value' => 'link-list',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_side_link-list_text',
                'min' => 1,
                'max' => 6,
                'layout' => 'block',
                'button_label' => 'Add Link',
                'sub_fields' => array(
                    array(
                        'key' => 'field_side_link-list_text',
                        'label' => 'Link Text',
                        'name' => 'side_link-list_text',
                        'type' => 'text',
                        'instructions' => '40 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 40,
                    ),
                    array(
                        'key' => 'field_side_link-list_url',
                        'label' => 'Link URL',
                        'name' => 'side_link-list_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_side_link-list_description',
                        'label' => 'Link Description',
                        'name' => 'side_link-list_description',
                        'type' => 'text',
                        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_side_link-list_include-more',
                'label' => 'Include "and more" at the end of the Link List?',
                'name' => 'side_link-list_include-more',
                'type' => 'true_false',
                'instructions' => 'This option is only available if you have 1-5 items in the link list.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_side_link-list',
                            'operator' => '<',
                            'value' => '6',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_side_cta',
                'label' => 'Call to Action Button',
                'name' => 'side_cta',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_side_cta_text',
                        'label' => 'Button Text',
                        'name' => 'side_cta_text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_side_cta_url',
                        'label' => 'Button URL',
                        'name' => 'side_cta_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_side_cta_target',
                        'label' => 'Open in New Window?',
                        'name' => 'side_cta_target',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_side_cta_description',
                        'label' => 'Link Description',
                        'name' => 'side_cta_description',
                        'type' => 'text',
                        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_side_image',
                'label' => 'Image Options',
                'name' => 'side_image',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_side_image_image',
                        'label' => 'Image',
                        'name' => 'side_image_image',
                        'type' => 'image',
                        'instructions' => 'Recommended image dimensions: 5120x2880. Minimum image dimensions: 1920x1080. The image will be automatically cropped to a 16:9 aspect ratio.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => 1920,
                        'min_height' => 1080,
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_side_image_alt-text',
                        'label' => 'Image Alt Text Override',
                        'name' => 'side_image_alt-text',
                        'type' => 'text',
                        'instructions' => 'Alt text (alternative text) refers to invisible description of images which are read aloud to blind users on a screen reader. If you want to define alt text that is different from the alt text defined for this image in the media library, you can do so here.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 125,
                    ),
                    array(
                        'key' => 'field_side_image_crop',
                        'label' => 'Vertical Crop',
                        'name' => 'side_image_crop',
                        'type' => 'select',
                        'instructions' => 'Your image will be cropped if necessary. Tell us if we should crop it from the top, middle, or bottom.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'top' => 'Crop from Top',
                            'center' => 'Crop from Center',
                            'bottom' => 'Crop from Bottom',
                        ),
                        'default_value' => array(
                            0 => 'center',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_side_image_position',
                'label' => 'Image & Text Position',
                'name' => 'side_image_position',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Image on Left, Text on Right',
                    'right' => 'Image on Right, Text on Left',
                ),
                'default_value' => array(
                    0 => 'left',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_side_image_anchor',
                'label' => 'Image Anchor Position',
                'name' => 'side_image_anchor',
                'type' => 'button_group',
                'instructions' => 'Where is the focus of your image content?',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Left',
                    'center' => 'Center',
                    'right' => 'Right',
                ),
                'allow_null' => 0,
                'default_value' => 'center',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_side_image_background-color',
                'label' => 'Background Color',
                'name' => 'side_image_background-color',
                'type' => 'select',
                'instructions' => 'This defines the background color of the text container.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/image-side',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS Hero Block
    acf_add_local_field_group(array(
        'key' => 'group_5ceef46c9fe82',
        'title' => 'Block: UAMS Slideshow',
        'fields' => array(
            array(
                'key' => 'field_hero_title',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Hero</h2>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5ceef47cfcbc0',
                'label' => 'Hero Slide(s)',
                'name' => 'hero',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'collapsed' => 'field_5ceef52afcbc1',
                'min' => 1,
                'max' => 4,
                'layout' => 'block',
                'button_label' => 'Add Slide',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hero_slide_intro-message',
                        'label' => '',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '<h3>Slide Options</h3>',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef9ae157a3',
                        'label' => 'Text Information',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'open' => 1,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef52afcbc1',
                        'label' => 'Heading',
                        'name' => 'hero_heading',
                        'type' => 'text',
                        'instructions' => '49 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 49,
                    ),
                    array(
                        'key' => 'field_5ceef54efcbc2',
                        'label' => 'Body',
                        'name' => 'hero_body',
                        'type' => 'textarea',
                        'instructions' => '177 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => 177,
                        'rows' => 4,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5ceef56ffcbc3',
                        'label' => 'Button Text',
                        'name' => 'hero_button_text',
                        'type' => 'text',
                        'instructions' => '29 character limit.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Learn More',
                        'placeholder' => 'Learn More',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '29',
                    ),
                    array(
                        'key' => 'field_5ceef58bfcbc4',
                        'label' => 'Button Link',
                        'name' => 'hero_button_url',
                        'type' => 'url',
                        'instructions' => 'Include http:// or https://',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5ceef56ffcbc3',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5ceef5adfcbc5',
                        'label' => 'Open in New Window?',
                        'name' => 'hero_button_target',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5ceef56ffcbc3',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5ceef5f6fcbc6',
                        'label' => 'Button Link Description',
                        'name' => 'hero_button_description',
                        'type' => 'text',
                        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5ceef56ffcbc3',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ceef79502cf2',
                        'label' => 'Image Information',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_hero_slide_image_intro-message',
                        'label' => '',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '<p>If you do not provide images for Tablet and Mobile image, the image you provide for Desktop will be automatically cropped for the other two views. This has a possibility of yielding undesirable results.</p>',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef617fcbc7',
                        'label' => 'Image Desktop',
                        'name' => 'image_desktop',
                        'type' => 'image',
                        'instructions' => 'Recommended dimensions: 2870x1536 or larger. Minimum dimensions: 1435x768. The image will be automatically cropped to a 1.8685:1 aspect ratio.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '1435',
                        'min_height' => '768',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_thumbnail' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef63ffcbc8',
                        'label' => 'Image Tablet',
                        'name' => 'image_tablet',
                        'type' => 'image',
                        'instructions' => 'Recommended dimensions: 1156x818 or larger. Minimum dimensions: 578x509. The image will be automatically cropped to a 1.4132:1 aspect ratio.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '578',
                        'min_height' => '409',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_thumbnail' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef656fcbc9',
                        'label' => 'Image Mobile',
                        'name' => 'image_mobile',
                        'type' => 'image',
                        'instructions' => 'Recommended dimensions: 1536x864 or larger. Minimum dimensions: 768x432. The image will be automatically cropped to a 16:9 aspect ratio.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '768',
                        'min_height' => '432',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_thumbnail' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef674fcbca',
                        'label' => 'Image Alt Text Override',
                        'name' => 'image_alt_text',
                        'type' => 'text',
                        'instructions' => 'Alt text (alternative text) refers to invisible description of images which are read aloud to blind users on a screen reader. If you want to define alt text that is different from the alt text defined for this image in the media library, you can do so here.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 125,
                    ),
                    array(
                        'key' => 'field_5ceef7b302cf3',
                        'label' => 'Color Option',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_permissions' => '',
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef69afcbcb',
                        'label' => 'Background Color',
                        'name' => 'background_color',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'auto' => 'Auto',
                            'blue' => 'Blue',
                            'green' => 'Green',
                            'teal-blue' => 'Teal Blue',
                            'eggplant' => 'Eggplant',
                            'maroon' => 'Maroon',
                            'orange' => 'Orange',
                        ),
                        'default_value' => array(
                            0 => 'auto',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/hero',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS CTA Bar Block
    acf_add_local_field_group(array(
        'key' => 'group_5cf938222421c',
        'title' => 'Block: UAMS CTA Bar',
        'fields' => array(
            array(
                'key' => 'field_cta-bar_intro-message',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Call-to-Action (CTA) Bar</h2>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_cta-bar_heading',
                'label' => 'Heading',
                'name' => 'cta-bar_heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_cta-bar_body',
                'label' => 'Body',
                'name' => 'cta-bar_body',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_cta-bar_button-text',
                'label' => 'Button Text',
                'name' => 'cta-bar_button-text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cf938b7e9df8',
                'label' => 'Button URL',
                'name' => 'cta-bar_button-url',
                'type' => 'text',
                'instructions' => 'Include http:// or https://',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_cta-bar_button-text',
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_cta-bar_button-target',
                'label' => 'Open in New Window?',
                'name' => 'cta-bar_button-target',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_cta-bar_button-text',
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_cta-bar_button-description',
                'label' => 'Button Link Description',
                'name' => 'cta-bar_button-description',
                'type' => 'text',
                'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_cta-bar_button-text',
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_cta-bar_layout',
                'label' => 'Layout',
                'name' => 'cta-bar_layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'cta-bar-centered' => 'Centered',
                    'cta-bar-weighted' => 'Weighted',
                ),
                'default_value' => array(
                    0 => 'cta-bar-centered',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_cta-bar_background-color',
                'label' => 'Background Color',
                'name' => 'cta-bar_background-color',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                    'bg-red' => 'Red',
                    'bg-black' => 'Black',
                    'bg-blue' => 'Blue',
                    'bg-green' => 'Green',
                    'bg-teal' => 'Teal',
                    'bg-eggplant' => 'Eggplant',
                    'bg-orange' => 'Orange',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_cta-bar_use-image',
                'label' => 'Use Background Image?',
                'name' => 'cta-bar_use-image',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_cta-bar_image',
                'label' => 'Image',
                'name' => 'cta-bar_image',
                'type' => 'image',
                'instructions' => 'Recommended image dimensions: 5120x2560. Minimum image dimensions: 1920x960. The image will be automatically cropped to a 2:1 aspect ratio.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_cta-bar_use-image',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => 1920,
                'min_height' => 960,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/cta',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS Call-Out Block
    acf_add_local_field_group(array(
        'key' => 'group_5cf980995ac56',
        'title' => 'Block: UAMS Call-Out',
        'fields' => array(
            array(
                'key' => 'field_call-out_intro-message',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Call-Out</h2>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_call-out_heading',
                'label' => 'Heading',
                'name' => 'call-out_heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_call-out_body',
                'label' => 'Body',
                'name' => 'call-out_body',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_out_background',
                'label' => 'Background Color',
                'name' => 'call-out_background-color',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                    'bg-red' => 'Red',
                    'bg-black' => 'Black',
                    'bg-blue' => 'Blue',
                    'bg-green' => 'Green',
                    'bg-teal' => 'Teal',
                    'bg-eggplant' => 'Eggplant',
                    'bg-orange' => 'Orange',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_call-out_use-image',
                'label' => 'Use Background Image?',
                'name' => 'call-out_use-image',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_call-out_image',
                'label' => 'Image',
                'name' => 'call-out_image',
                'type' => 'image',
                'instructions' => 'Recommended image dimensions: 5120x1920. Minimum image dimensions: 1920x720. The image will be automatically cropped to a 8:3 aspect ratio.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_call-out_use-image',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => 1920,
                'min_height' => 720,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/call-out',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS Action Bar Block
    acf_add_local_field_group(array(
        'key' => 'group_5cf9847426451',
        'title' => 'Block: UAMS Action Bar',
        'fields' => array(
            array(
                'key' => 'field_action-bar_intro-message',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Action Bar</h2>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_action-bar_heading',
                'label' => 'Heading',
                'name' => 'action-bar_heading',
                'type' => 'text',
                'instructions' => 'This heading is here for accessibility purposes only and will not be visible.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Important Links',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_action-bar_background-color',
                'label' => 'Background Color',
                'name' => 'action-bar_background-color',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                    'bg-red' => 'Red',
                    'bg-black' => 'Black',
                    'bg-blue' => 'Blue',
                    'bg-green' => 'Green',
                    'bg-teal' => 'Teal',
                    'bg-eggplant' => 'Eggplant',
                    'bg-orange' => 'Orange',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_action-bar_section',
                'label' => 'Sections',
                'name' => 'action-bar_section',
                'type' => 'repeater',
                'instructions' => 'You may have either 3 or 4 sections.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_section_heading',
                'min' => 3,
                'max' => 4,
                'layout' => 'block',
                'button_label' => 'Add Section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_action-bar_section_heading',
                        'label' => 'Heading',
                        'name' => 'action-bar_section_heading',
                        'type' => 'text',
                        'instructions' => '46 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 46,
                    ),
                    array(
                        'key' => 'field_action-bar_section_body',
                        'label' => 'Body',
                        'name' => 'action-bar_section_body',
                        'type' => 'text',
                        'instructions' => '67 character limit',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 67,
                    ),
                    array(
                        'key' => 'field_action-bar_section_button-text',
                        'label' => 'Button Text',
                        'name' => 'action-bar_section_button-text',
                        'type' => 'text',
                        'instructions' => 'When the browser window is small, this button will be the only thing from this section that is displayed, so ensure that your Button Text will make sense on its own.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 31,
                    ),
                    array(
                        'key' => 'field_action-bar_section_button-url',
                        'label' => 'Button URL',
                        'name' => 'action-bar_section_button-url',
                        'type' => 'url',
                        'instructions' => 'Include http:// or https://.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_action-bar_section_button-target',
                        'label' => 'Open in New Window?',
                        'name' => 'action-bar_section_button-target',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_action-bar_section_button-description',
                        'label' => 'Button Link Description',
                        'name' => 'action-bar_section_button-description',
                        'type' => 'text',
                        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/action-bar',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS Text & Image Overlay Block
    acf_add_local_field_group(array(
        'key' => 'group_5cfa9e13cb394',
        'title' => 'Block: UAMS Text & Image Overlay',
        'fields' => array(
            array(
                'key' => 'field_overlay_intro-message',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Text-Image Overlay</h2>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_overlay_section',
                'label' => 'Sections',
                'name' => 'overlay_section',
                'type' => 'repeater',
                'instructions' => 'You may have either one or two sections. If you only have one section, it will display full-width. Two sections will be displayed beside each other, half the width of the viewport.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_overlay_section_heading',
                'min' => 1,
                'max' => 2,
                'layout' => 'block',
                'button_label' => 'Add Section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_overlay_section_heading',
                        'label' => 'Heading',
                        'name' => 'overlay_section_heading',
                        'type' => 'text',
                        'instructions' => '32 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 32,
                    ),
                    array(
                        'key' => 'field_overlay_section_body',
                        'label' => 'Body',
                        'name' => 'overlay_section_body',
                        'type' => 'text',
                        'instructions' => '280 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 280,
                    ),
                    array(
                        'key' => 'field_overlay_section_button-text',
                        'label' => 'Button Text',
                        'name' => 'overlay_section_button-text',
                        'type' => 'text',
                        'instructions' => '27 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 26,
                    ),
                    array(
                        'key' => 'field_overlay_section_button-url',
                        'label' => 'Button URL',
                        'name' => 'overlay_section_button-url',
                        'type' => 'url',
                        'instructions' => 'Include http:// or https://.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_overlay_section_button-target',
                        'label' => 'Open in New Window?',
                        'name' => 'overlay_section_button-target',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_overlay_section_button-description',
                        'label' => 'Button Link Description',
                        'name' => 'overlay_section_button-description',
                        'type' => 'text',
                        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_overlay_section_background-color',
                        'label' => 'Background Color',
                        'name' => 'overlay_section_background-color',
                        'type' => 'select',
                        'instructions' => 'Each section should use a different color. If this module is adjacent to another module with a background color, the adjacent modules/sections should all use different colors. If this module is adjacent to the footer, the color red should not be used, as the footer is red.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'bg-red' => 'Red',
                            'bg-black' => 'Black',
                            'bg-blue' => 'Blue',
                            'bg-green' => 'Green',
                            'bg-teal' => 'Teal',
                            'bg-eggplant' => 'Eggplant',
                            'bg-orange' => 'Orange',
                        ),
                        'default_value' => array(
                            0 => 'bg-black',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_overlay_section_image',
                        'label' => 'Image',
                        'name' => 'overlay_section_image',
                        'type' => 'image',
                        'instructions' => 'Recommended image dimensions for single section: 5120x2560. Recommended image dimensions for two sections: 2560x1920. Minimum image dimensions: 1920x720. If there are two sections, the image will be automatically cropped to a 4:3 aspect ratio. If there is one section, the image will be automatically cropped to a 8:3 aspect ratio.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => 1920,
                        'min_height' => 720,
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/text-overlay',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS Stacked Image & Text Block
    acf_add_local_field_group(array(
        'key' => 'group_5cfab4f342f6d',
        'title' => 'Block: UAMS Stacked Image & Text',
        'fields' => array(
            array(
                'key' => 'field_stacked_intro-message',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h2>Stacked Image &amp; Text</h2>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_stacked_heading',
                'label' => 'Module Heading',
                'name' => 'stacked_heading',
                'type' => 'text',
                'instructions' => 'Even if this heading is hidden, it is necessary for accessibility.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_stacked_hide-heading',
                'label' => 'Hide the Module Heading?',
                'name' => 'stacked_hide-heading',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_stacked_background-color',
                'label' => 'Background Color',
                'name' => 'stacked_background-color',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_stacked_section',
                'label' => 'Items',
                'name' => 'stacked_section',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 4,
                'max' => 4,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_stacked_section_heading',
                        'label' => 'Heading',
                        'name' => 'stacked_section_heading',
                        'type' => 'text',
                        'instructions' => '78 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 78,
                    ),
                    array(
                        'key' => 'field_stacked_section_body',
                        'label' => 'Body',
                        'name' => 'stacked_section_body',
                        'type' => 'textarea',
                        'instructions' => '179 character limit.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '179',
                        'rows' => 3,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_stacked_section_image',
                        'label' => 'Image',
                        'name' => 'stacked_section_image',
                        'type' => 'image',
                        'instructions' => 'Recommended image dimensions: 910x512. Minimum image dimensions: 455x256. The image will automatically be cropped to a 16:9 aspect ratio.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => 455,
                        'min_height' => 256,
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_stacked_section_alt-override',
                        'label' => 'Image Alt Text Override',
                        'name' => 'stacked_section_alt-override',
                        'type' => 'text',
                        'instructions' => 'Alt text (alternative text) refers to invisible description of images which are read aloud to blind users on a screen reader. If you want to define alt text that is different from the alt text defined for this image in the media library, you can do so here.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 125,
                    ),
                    array(
                        'key' => 'field_stacked_section_button-text',
                        'label' => 'Button Text',
                        'name' => 'stacked_section_button-text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_stacked_section_button-url',
                        'label' => 'Button URL',
                        'name' => 'stacked_section_button-url',
                        'type' => 'url',
                        'instructions' => 'Include http:// or https://.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_stacked_section_button-target',
                        'label' => 'Open in New Window?',
                        'name' => 'stacked_section_button-target',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_stacked_section_button-description',
                        'label' => 'Button Link Description',
                        'name' => 'stacked_section_button-description',
                        'type' => 'text',
                        'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/text-stacked',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    
    
    endif;