<?php

/*
 *
 * Custom ACF Blocks
 * 
 */

add_action('acf/init', 'uams_register_blocks');
function uams_register_blocks() {

    // check function exists.
    if( function_exists('acf_register_block_type') ) {

        // register a hero block.
        acf_register_block_type(array(
            'name'              => 'hero',
            'title'             => __('UAMS Hero'),
            'description'       => __('UAMS Hero / Slideshow.'),
            'category'          => 'common',
            'icon'              => 'images-alt2',
            'keywords'          => array('uams', 'slides', 'slideshow', 'hero'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/hero.php',
        ));
        // acf_register_block_type(array(
        //     'name'              => 'image-side',
        //     'title'             => __('UAMS Image-Text'),
        //     'description'       => __('Side-by-Side Image & Text.'),
        //     'category'          => 'common',
        //     'icon'              => 'id',
        //     'keywords'          => array('uams', 'text', 'image', 'side'),
        //     'mode'              => 'auto',
        //     'align'             => 'full',
        //     'render_template'   => 'blocks/side.php',
        // ));
        // acf_register_block_type(array(
        //     'name'              => 'image-stack',
        //     'title'             => __('UAMS Image Stack'),
        //     'description'       => __('Stacked Image & Text'),
        //     'category'          => 'common',
        //     'icon'              => 'screenoptions',
        //     'keywords'          => array('uams', 'text', 'image', 'stack'),
        //     'mode'              => 'auto',
        //     'align'             => 'full',
        //     'render_template'   => 'blocks/stack.php',
        // ));
        // acf_register_block_type(array(
        //     'name'              => 'image-overlay',
        //     'title'             => __('UAMS Overlay'),
        //     'description'       => __('Overlaid Image & Text.'),
        //     'category'          => 'common',
        //     'icon'              => 'format-image',
        //     'keywords'          => array('uams', 'text', 'image', 'overlay'),
        //     'mode'              => 'auto',
        //     'align'             => 'full',
        //     'render_template'   => 'blocks/overlay.php',
        // ));
        acf_register_block_type(array(
            'name'              => 'cta',
            'title'             => __('UAMS CTA'),
            'description'       => __('Call-to-Action (CTA) Bar.'),
            'category'          => 'common',
            'icon'              => 'format-status',
            'keywords'          => array('uams', 'cta', 'button'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/cta.php',
        ));
        acf_register_block_type(array(
            'name'              => 'call-out',
            'title'             => __('UAMS Call-Out'),
            'description'       => __('Call-Out.'),
            'category'          => 'common',
            'icon'              => 'megaphone',
            'keywords'          => array('uams', 'callout', 'call-out', 'text'),
            'mode'              => 'auto',
            'align'             => 'full',
            'render_template'   => 'blocks/call-out.php',
        ));
        // acf_register_block_type(array(
        //     'name'              => 'block',
        //     'title'             => __('UAMS Block'),
        //     'description'       => __('A custom hero block.'),
        //     'category'          => 'common',
        //     'icon'              => '',
        //     'keywords'          => array('uams', 'block'),
        //     'mode'              => 'auto',
        //     'align'             => 'full',
        //     'render_template'   => 'blocks/block.php',
		// ));
    }
}

if( function_exists('acf_add_local_field_group') ):

    // acf_add_local_field_group(array(
    //     'key' => 'group_5cefe899bb3bd',
    //     'title' => 'Block: Call-to-Action Bar',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_cta_title',
    //             'label' => '',
    //             'name' => '',
    //             'type' => 'message',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'message' => '<h3>Call-to-Action Bar</h3>',
    //             'new_lines' => 'wpautop',
    //             'esc_html' => 0,
    //         ),
    //         array(
    //             'key' => 'field_5cefe8c962315',
    //             'label' => 'Layout',
    //             'name' => 'cta_layout',
    //             'type' => 'select',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'choices' => array(
    //             ),
    //             'default_value' => array(
    //             ),
    //             'allow_null' => 0,
    //             'multiple' => 0,
    //             'ui' => 0,
    //             'return_format' => 'value',
    //             'ajax' => 0,
    //             'placeholder' => '',
    //         ),
    //         array(
    //             'key' => 'field_5cefe8ec62316',
    //             'label' => 'Heading',
    //             'name' => 'cta_heading',
    //             'type' => 'text',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'placeholder' => '',
    //             'prepend' => '',
    //             'append' => '',
    //             'maxlength' => '',
    //         ),
    //         array(
    //             'key' => 'field_5cefe8f662317',
    //             'label' => 'Body',
    //             'name' => 'cta_body',
    //             'type' => 'wysiwyg',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'tabs' => 'all',
    //             'toolbar' => 'full',
    //             'media_upload' => 0,
    //             'delay' => 0,
    //         ),
    //         array(
    //             'key' => 'field_5cefe91862318',
    //             'label' => 'Call-to-Action',
    //             'name' => 'cta_cta',
    //             'type' => 'group',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'layout' => 'block',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_5cefe95c6231a',
    //                     'label' => 'Text',
    //                     'name' => 'text',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe9676231b',
    //                     'label' => 'URL',
    //                     'name' => 'url',
    //                     'type' => 'url',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe9706231c',
    //                     'label' => 'New Window?',
    //                     'name' => 'target',
    //                     'type' => 'true_false',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'message' => '',
    //                     'default_value' => 0,
    //                     'ui' => 1,
    //                     'ui_on_text' => '',
    //                     'ui_off_text' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe9876231d',
    //                     'label' => 'Description',
    //                     'name' => 'description',
    //                     'type' => 'text',
    //                     'instructions' => 'Used for accessibility',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //             ),
    //         ),
    //         array(
    //             'key' => 'field_5cefe93c62319',
    //             'label' => 'Color Scheme',
    //             'name' => 'cta_color_scheme',
    //             'type' => 'select',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'choices' => array(
    //                 'auto' => 'Auto',
    //                 'blue' => 'Blue',
    //                 'green' => 'Green',
    //                 'teal-blue' => 'Teal Blue',
    //                 'eggplant' => 'Eggplant',
    //                 'maroon' => 'Maroon',
    //                 'orange' => 'Orange',
    //             ),
    //             'default_value' => array(
    //             ),
    //             'allow_null' => 0,
    //             'multiple' => 0,
    //             'ui' => 0,
    //             'return_format' => 'value',
    //             'ajax' => 0,
    //             'placeholder' => '',
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'block',
    //                 'operator' => '==',
    //                 'value' => 'acf/cta',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 0,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'left',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => '',
    //     'active' => true,
    //     'description' => '',
    //     'acfe_display_title' => '',
    //     'acfe_autosync' => '',
    //     'acfe_permissions' => '',
    //     'acfe_note' => '',
    //     'acfcdt_manage_table_definition' => 0,
    //     'acfcdt_table_definition_file_name' => 'table_356x5cefe899c8c67',
    //     'acfe_meta' => '',
    // ));
    
    // acf_add_local_field_group(array(
    //     'key' => 'group_5cefe61e287f0',
    //     'title' => 'Block: Overlaid Image & Text',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_overlay_image_title',
    //             'label' => '',
    //             'name' => '',
    //             'type' => 'message',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'message' => '<h3>Overlaid Image & Text</h3>',
    //             'new_lines' => 'wpautop',
    //             'esc_html' => 0,
    //         ),
    //         array(
    //             'key' => 'field_5cefe62861ec5',
    //             'label' => 'Block',
    //             'name' => 'overlaid_block',
    //             'type' => 'repeater',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'collapsed' => 'field_5cefe63961ec6',
    //             'min' => 0,
    //             'max' => 0,
    //             'layout' => 'block',
    //             'button_label' => 'Add Image',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_5cefe63961ec6',
    //                     'label' => 'Heading',
    //                     'name' => 'heading',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe65e61ec7',
    //                     'label' => 'Body',
    //                     'name' => 'body',
    //                     'type' => 'textarea',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'maxlength' => '',
    //                     'rows' => '',
    //                     'new_lines' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe68261ec8',
    //                     'label' => 'Call-to-Action',
    //                     'name' => 'cta',
    //                     'type' => 'group',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'layout' => 'block',
    //                     'sub_fields' => array(
    //                         array(
    //                             'key' => 'field_5cefe69661ec9',
    //                             'label' => 'Text',
    //                             'name' => 'cta_text',
    //                             'type' => 'text',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe6a661eca',
    //                             'label' => 'Body',
    //                             'name' => 'cta_body',
    //                             'type' => 'text',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe6b161ecb',
    //                             'label' => 'New Window?',
    //                             'name' => 'cta_target',
    //                             'type' => 'text',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe6c461ecc',
    //                             'label' => 'Description',
    //                             'name' => 'cta_description',
    //                             'type' => 'text',
    //                             'instructions' => 'Used for accessibility',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                     ),
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe6f361ecd',
    //                     'label' => 'Image',
    //                     'name' => 'overlaid_image',
    //                     'type' => 'group',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                             'layout' => 'block',
    //                     'sub_fields' => array(
    //                         array(
    //                             'key' => 'field_5cefe70761ece',
    //                             'label' => 'Image',
    //                             'name' => 'image',
    //                             'type' => 'image',
    //                             'instructions' => '',
    //                             'required' => 1,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'return_format' => 'array',
    //                             'preview_size' => 'thumbnail',
    //                             'library' => 'all',
    //                             'min_width' => '',
    //                             'min_height' => '',
    //                             'min_size' => '',
    //                             'max_width' => '',
    //                             'max_height' => '',
    //                             'max_size' => '',
    //                             'mime_types' => '',
    //                             'acfe_thumbnail' => 0,
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe71a61ecf',
    //                             'label' => 'Alt Text',
    //                             'name' => 'alt_text',
    //                             'type' => 'text',
    //                             'instructions' => 'Overrides default image alt text',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                     ),
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe74a61ed0',
    //                     'label' => 'Color Scheme',
    //                     'name' => 'overlaid_color_scheme',
    //                     'type' => 'select',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'choices' => array(
    //                         'auto' => 'Auto',
    //                         'blue' => 'Blue',
    //                         'green' => 'Green',
    //                         'teal-blue' => 'Teal Blue',
    //                         'eggplant' => 'Eggplant',
    //                         'maroon' => 'Maroon',
    //                         'orange' => 'Orange',
    //                     ),
    //                     'default_value' => array(
    //                         0 => 'auto',
    //                     ),
    //                     'allow_null' => 0,
    //                     'multiple' => 0,
    //                     'ui' => 0,
    //                     'return_format' => 'value',
    //                     'ajax' => 0,
    //                     'placeholder' => '',
    //                 ),
    //             ),
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'block',
    //                 'operator' => '==',
    //                 'value' => 'acf/cta',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 0,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'left',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => '',
    //     'active' => true,
    //     'description' => '',
    // ));
    
    // acf_add_local_field_group(array(
    //     'key' => 'group_5cefe13df1b97',
    //     'title' => 'Block: Side-by-Side Image & Text',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_side_image_title',
    //             'label' => '',
    //             'name' => '',
    //             'type' => 'message',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'message' => '<h3>Side-by-Side Image & Text</h3>',
    //             'new_lines' => 'wpautop',
    //             'esc_html' => 0,
    //         ),
    //         array(
    //             'key' => 'field_5cefe14bfe21d',
    //             'label' => 'Heading',
    //             'name' => 'side_image_heading',
    //             'type' => 'text',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'placeholder' => '',
    //             'prepend' => '',
    //             'append' => '',
    //             'maxlength' => '',
    //         ),
    //         array(
    //             'key' => 'field_5cefe159fe21e',
    //             'label' => 'Body',
    //             'name' => 'side_image_body',
    //             'type' => 'wysiwyg',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'tabs' => 'all',
    //             'toolbar' => 'basic',
    //             'media_upload' => 1,
    //             'delay' => 0,
    //         ),
    //         array(
    //             'key' => 'field_5cefe175fe21f',
    //             'label' => 'Link List',
    //             'name' => 'side_image_link_list',
    //             'type' => 'repeater',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'collapsed' => 'field_5cefe18efe220',
    //             'min' => 0,
    //             'max' => 0,
    //             'layout' => 'block',
    //             'button_label' => '',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_5cefe18efe220',
    //                     'label' => 'Text',
    //                     'name' => 'side_image_link_list_text',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe1adfe221',
    //                     'label' => 'URL',
    //                     'name' => 'side_image_link_list_url',
    //                     'type' => 'url',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe1cbfe222',
    //                     'label' => 'Description',
    //                     'name' => 'side_image_link_list_description',
    //                     'type' => 'text',
    //                     'instructions' => 'Used for accessibility',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //             ),
    //         ),
    //         array(
    //             'key' => 'field_5cefe20efe223',
    //             'label' => 'Link List (include more)',
    //             'name' => 'link_list_include_more',
    //             'type' => 'true_false',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'message' => '',
    //             'default_value' => 0,
    //             'ui' => 1,
    //             'ui_on_text' => '',
    //             'ui_off_text' => '',
    //         ),
    //         array(
    //             'key' => 'field_5cefe23afe224',
    //             'label' => 'Call to Action',
    //             'name' => 'call_to_action',
    //             'type' => 'group',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'layout' => 'block',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_5cefe258fe225',
    //                     'label' => 'Text',
    //                     'name' => 'cta_text',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe280fe226',
    //                     'label' => 'URL',
    //                     'name' => 'cta_url',
    //                     'type' => 'url',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe293fe227',
    //                     'label' => 'New Window?',
    //                     'name' => 'cta_target',
    //                     'type' => 'true_false',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'message' => '',
    //                     'default_value' => 0,
    //                     'ui' => 1,
    //                     'ui_on_text' => '',
    //                     'ui_off_text' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe2b8fe228',
    //                     'label' => 'Description',
    //                     'name' => 'cta_description',
    //                     'type' => 'text',
    //                     'instructions' => 'Used for accessibility',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //             ),
    //         ),
    //         array(
    //             'key' => 'field_5cefe2e8fe229',
    //             'label' => 'Image',
    //             'name' => 'side_image_image',
    //             'type' => 'group',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'layout' => 'block',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_5cefe318fe22a',
    //                     'label' => 'Image',
    //                     'name' => 'image',
    //                     'type' => 'image',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'return_format' => 'id',
    //                     'preview_size' => 'thumbnail',
    //                     'library' => 'all',
    //                     'min_width' => '',
    //                     'min_height' => '',
    //                     'min_size' => '',
    //                     'max_width' => '',
    //                     'max_height' => '',
    //                     'max_size' => '',
    //                     'mime_types' => '',
    //                     'acfe_thumbnail' => 0,
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe332fe22b',
    //                     'label' => 'Alt Text',
    //                     'name' => 'alt_text',
    //                     'type' => 'text',
    //                     'instructions' => 'Overrides image alt text',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //             ),
    //         ),
    //         array(
    //             'key' => 'field_5cefebddf3ceb',
    //             'label' => 'Position',
    //             'name' => 'side_image_position',
    //             'type' => 'button_group',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'choices' => array(
    //                 'left' => 'Left',
    //                 'right' => 'Right',
    //             ),
    //             'allow_null' => 0,
    //             'default_value' => '',
    //             'layout' => 'horizontal',
    //             'return_format' => 'value',
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'block',
    //                 'operator' => '==',
    //                 'value' => 'acf/image-side',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 0,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'left',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => '',
    //     'active' => true,
    //     'description' => '',
    // ));
    
    // acf_add_local_field_group(array(
    //     'key' => 'group_5cefe3cedd19e',
    //     'title' => 'Block: Stacked Image & Text',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_stacked_image_title',
    //             'label' => '',
    //             'name' => '',
    //             'type' => 'message',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'message' => '<h3>Stacked Image & Text</h3>',
    //             'new_lines' => 'wpautop',
    //             'esc_html' => 0,
    //         ),
    //         array(
    //             'key' => 'field_5cefe3f3c4064',
    //             'label' => 'Stack',
    //             'name' => 'stacked_image_block',
    //             'type' => 'repeater',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),

    //             'collapsed' => '',
    //             'min' => 2,
    //             'max' => 4,
    //             'layout' => 'block',
    //             'button_label' => '',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_5cefe449c4065',
    //                     'label' => 'Heading',
    //                     'name' => 'heading',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 1,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
        
        
        
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe45bc4066',
    //                     'label' => 'Body',
    //                     'name' => 'body',
    //                     'type' => 'textarea',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
        
        
        
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'maxlength' => '',
    //                     'rows' => '',
    //                     'new_lines' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe4a3c4067',
    //                     'label' => 'Call-to-Action',
    //                     'name' => 'cta',
    //                     'type' => 'group',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
        
        
        
    //                     'layout' => 'block',
    //                     'sub_fields' => array(
    //                         array(
    //                             'key' => 'field_5cefe4c8c4068',
    //                             'label' => 'Text',
    //                             'name' => 'cta_text',
    //                             'type' => 'text',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
                
                
                
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe4dfc4069',
    //                             'label' => 'URL',
    //                             'name' => 'cta_url',
    //                             'type' => 'url',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
                
                
                
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe4ecc406a',
    //                             'label' => 'New Window?',
    //                             'name' => 'cta_target',
    //                             'type' => 'true_false',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
                
                
                
    //                             'message' => '',
    //                             'default_value' => 0,
    //                             'ui' => 1,
    //                             'ui_on_text' => '',
    //                             'ui_off_text' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe50ac406b',
    //                             'label' => 'Description',
    //                             'name' => 'cta_description',
    //                             'type' => 'text',
    //                             'instructions' => 'Used for accessibility',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
                
                
                
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                     ),
    //                 ),
    //                 array(
    //                     'key' => 'field_5cefe534c406c',
    //                     'label' => 'Image',
    //                     'name' => 'image_info',
    //                     'type' => 'group',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'layout' => 'block',
    //                     'sub_fields' => array(
    //                         array(
    //                             'key' => 'field_5cefe594c406f',
    //                             'label' => 'Image',
    //                             'name' => 'image',
    //                             'type' => 'image',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'return_format' => 'id',
    //                             'preview_size' => 'thumbnail',
    //                             'library' => 'all',
    //                             'min_width' => '',
    //                             'min_height' => '',
    //                             'min_size' => '',
    //                             'max_width' => '',
    //                             'max_height' => '',
    //                             'max_size' => '',
    //                             'mime_types' => '',
    //                             'acfe_thumbnail' => 0,
    //                         ),
    //                         array(
    //                             'key' => 'field_5cefe5a0c4070',
    //                             'label' => 'Alt Text',
    //                             'name' => 'alt_text',
    //                             'type' => 'text',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                     ),
    //                 ),
    //             ),
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'block',
    //                 'operator' => '==',
    //                 'value' => 'acf/image-stack',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 0,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'left',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => '',
    //     'active' => true,
    //     'description' => '',
    // ));

    // Add local field group for UAMS Hero Block
    acf_add_local_field_group(array(
        'key' => 'group_5ceef46c9fe82',
        'title' => 'Block: UAMS Slideshow',
        'fields' => array(
            array(
                'key' => 'field_hero_title',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h3>Hero / Slideshow</h3>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5ceef47cfcbc0',
                'label' => 'Hero',
                'name' => 'hero',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'collapsed' => 'field_5ceef52afcbc1',
                'min' => 1,
                'max' => 4,
                'layout' => 'block',
                'button_label' => 'Add Slide',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ceef9ae157a3',
                        'label' => 'Text Information',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'open' => 1,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef52afcbc1',
                        'label' => 'Heading',
                        'name' => 'hero_heading',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 60,
                    ),
                    array(
                        'key' => 'field_5ceef54efcbc2',
                        'label' => 'Body',
                        'name' => 'hero_body',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => 300,
                        'rows' => 4,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5ceef56ffcbc3',
                        'label' => 'Button Text',
                        'name' => 'hero_button_text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Learn More',
                        'placeholder' => 'Learn More',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ceef58bfcbc4',
                        'label' => 'Button Link',
                        'name' => 'hero_button_url',
                        'type' => 'url',
                        'instructions' => 'include http:// or https://',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5ceef5adfcbc5',
                        'label' => 'Open in New Window?',
                        'name' => 'hero_button_target',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5ceef5f6fcbc6',
                        'label' => 'Button Description',
                        'name' => 'hero_button_description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ceef79502cf2',
                        'label' => 'Image Information',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef617fcbc7',
                        'label' => 'Image Desktop',
                        'name' => 'image_desktop',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_thumbnail' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef63ffcbc8',
                        'label' => 'Image Tablet',
                        'name' => 'image_tablet',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_thumbnail' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef656fcbc9',
                        'label' => 'Image Mobile',
                        'name' => 'image_mobile',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_validate' => '',
                        'acfe_update' => '',
                        'acfe_permissions' => '',
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_thumbnail' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef674fcbca',
                        'label' => 'Image Alt Text',
                        'name' => 'image_alt_text',
                        'type' => 'text',
                        'instructions' => 'Description of image for accessibility',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ceef7b302cf3',
                        'label' => 'Color Option',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_permissions' => '',
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5ceef69afcbcb',
                        'label' => 'Background Color',
                        'name' => 'background_color',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'auto' => 'Auto',
                            'blue' => 'Blue',
                            'green' => 'Green',
                            'teal-blue' => 'Teal Blue',
                            'eggplant' => 'Eggplant',
                            'maroon' => 'Maroon',
                            'orange' => 'Orange',
                        ),
                        'default_value' => array(
                            0 => 'auto',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/hero',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS CTA Bar Block
    acf_add_local_field_group(array(
        'key' => 'group_5cf938222421c',
        'title' => 'UAMS CTA Bar',
        'fields' => array(
            array(
                'key' => 'field_5cf9382be9df5',
                'label' => 'Heading',
                'name' => 'cta-bar_heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cf9385fe9df6',
                'label' => 'Body',
                'name' => 'cta-bar_body',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5cf93896e9df7',
                'label' => 'Button Text',
                'name' => 'cta-bar_button-text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cf938b7e9df8',
                'label' => 'Button URL',
                'name' => 'cta-bar_button-url',
                'type' => 'text',
                'instructions' => 'Include http:// or https://',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5cf93896e9df7',
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cf938cde9df9',
                'label' => 'Open in New Window?',
                'name' => 'cta-bar_button-target',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5cf93896e9df7',
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5cf938fee9dfa',
                'label' => 'Button Description',
                'name' => 'cta-bar_button-description',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5cf93896e9df7',
                            'operator' => '!=empty',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cf93919e9dfb',
                'label' => 'Layout',
                'name' => 'cta-bar_layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'cta-bar-centered' => 'Centered',
                    'cta-bar-weighted' => 'Weighted',
                ),
                'default_value' => array(
                    0 => 'cta-bar-centered',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5cf93a28e9dfd',
                'label' => 'Background Color',
                'name' => 'cta-bar_background-color',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                    'bg-red' => 'Red',
                    'bg-black' => 'Black',
                    'bg-blue' => 'Blue',
                    'bg-green' => 'Green',
                    'bg-teal' => 'Teal',
                    'bg-eggplant' => 'Eggplant',
                    'bg-orange' => 'Orange',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5cf940a64efcc',
                'label' => 'Use Background Image?',
                'name' => 'cta-bar_use-image',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5cf940c24efcd',
                'label' => 'Image',
                'name' => 'cta-bar_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5cf940a64efcc',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/cta',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Add local field group for UAMS Call-Out Block
    acf_add_local_field_group(array(
        'key' => 'group_5cf980995ac56',
        'title' => 'UAMS Call-Out',
        'fields' => array(
            array(
                'key' => 'field_5cf980995d30b',
                'label' => 'Heading',
                'name' => 'call-out_heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cf980995d342',
                'label' => 'Body',
                'name' => 'call-out_body',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5cf980995d50b',
                'label' => 'Background Color',
                'name' => 'call-out_background-color',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'bg-white' => 'White',
                    'bg-gray' => 'Gray',
                    'bg-red' => 'Red',
                    'bg-black' => 'Black',
                    'bg-blue' => 'Blue',
                    'bg-green' => 'Green',
                    'bg-teal' => 'Teal',
                    'bg-eggplant' => 'Eggplant',
                    'bg-orange' => 'Orange',
                ),
                'default_value' => array(
                    0 => 'bg-white',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5cf980995d56e',
                'label' => 'Use Background Image?',
                'name' => 'call-out_use-image',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5cf980995d5d1',
                'label' => 'Image',
                'name' => 'call-out_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5cf980995d56e',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/call-out',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    
    
    endif;