<?php

/*
 *
 * Custom Meta box
 * 
 */

// Subsection Attribute
// add_filter( 'rwmb_meta_boxes', 'uamswp_register_meta_boxes' );
// function uamswp_register_meta_boxes( $meta_boxes ) {
// 	$meta_boxes[] = array (
// 		'title' => 'Page Settings',
// 		'id' => 'page-settings',
// 		'post_types' => array(
// 			'page',
// 		),
// 		'context' => 'side',
// 		'priority' => 'high',
// 		'status' => 'publish',
// 		'fields' => array(
			
// 			array (
// 				'id' => 'page_subsection',
// 				'name' => 'Subsection',
// 				'type' => 'checkbox',
// 				'desc' => 'Page is a subsection',
// 			),
// 		),
// 	);
// 	return $meta_boxes;
// }

// // Register settings page. In this case, it's a theme options page
// add_filter( 'mb_settings_pages', 'uamswp_options_page' );
// function uamswp_options_page( $settings_pages ) {
//     $settings_pages[] = array(
//         'id'          => 'uamswp_options',
//         'option_name' => 'uamswp_options',
//         'menu_title'  => 'UAMS Settings',
//         'icon_url'    => 'dashicons-admin-generic',
//     );
//     return $settings_pages;
// }

// // Register meta boxes and fields for settings page
// add_filter( 'rwmb_meta_boxes', 'uamswp_options_meta_boxes' );
// function uamswp_options_meta_boxes( $meta_boxes ) {
//     $meta_boxes[] = array(
//         'id'             => 'uamswp_settings',
//         'title'          => 'Settings',
//         'settings_pages' => 'uamswp_options',
//         // 'tab'            => 'faq',
//         'fields'         => array( 
//             array(
//                 'id'             => 'uamswp_template',
//                 'name'          => 'Theme Style',
//                 'type'            => 'select',
//                 'placeholder'     => 'Select a site',
//                 // Array of 'value' => 'Label' pairs
//                 'options'         => array(
//                     'uams'       => 'UAMS.edu',
//                     'health'     => 'UAMSHealth',
//                     'inside'     => 'Inside',
//                     'institute'  => 'Institute',
//                     //'other'      => 'Other',
//                 ),
//             ),

//             array(
//                 'id'             => 'uamswp_location',
//                 'name'           => 'Site Location',
//                 'type'            => 'select',
//                 // 'placeholder'     => 'Select a location',
//                 // Array of 'value' => 'Label' pairs
//                 'options'         => array(
//                     'uams'                  => 'Main Campus',
//                     'nw-campus'             => 'Northwest Campus',
//                     'regional-campus-e'     => 'Regional Campus - East',
//                     'regional-campus-ne'    => 'Regional Campus - Northeast',
//                     'regional-campus-nw'    => 'Regional Campus - Northwest',
//                     'regional-campus-nc'    => 'Regional Campus - North Central',
//                     'regional-campus-s'     => 'Regional Campus - South',
//                     'regional-campus-sw'    => 'Regional Campus - Southwest',
//                     'regional-campus-sc'    => 'Regional Campus - South Central',
//                     'regional-campus-w'     => 'Regional Campus - West',
//                 ),
//                 'std'       => 'uams',
//                 'hidden' => array( 'uamswp_template', '!=', 'uams' ),
//             ),

//             array(
//                 'id'             => 'uamswp_institute',
//                 'name'           => 'UAMS Institute',
//                 'type'            => 'select',
//                 'placeholder'     => 'Select an Institute',
//                 // Array of 'value' => 'Label' pairs
//                 'options'         => array(
//                     'institute_aging'       => 'Donald W. Reynolds Institute on Aging',
//                     'institute_eye'         => 'Harvey & Bernice Jones Eye Institute',
//                     'institute_spine'       => 'Jackson T. Stephens Spine & Neurosciences Institute',
//                     'institute_digi-health' => 'Institute for Digital Health & Innovation',
//                     'institute_pri'         => 'Psychiatric Research Institute',
//                     'institute_tri'         => 'Translational Research Institute',
//                     'institute_cancer'      => 'Winthrop P. Rockefeller Cancer Institute',
//                 ),
//                 'hidden' => array( 'uamswp_template', '!=', 'institute' ),
//             ),

//             array(
//                 'id'             => 'uamswp_uams_subsite',
//                 'name'           => 'Organization',
//                 'type'           => 'select_advanced',
//                 'placeholder'     => 'Select an organization',
//                 // Array of 'value' => 'Label' pairs
//                 'options'         => array(
//                     'health-prof'           => 'College of Health Professions',
//                     'medicine'              => 'College of Medicine',
//                     'medicine_emergency-medicine'   => 'College of Medicine -  Emergency Medicine',
//                     'medicine_pediatrics'           => 'College of Medicine - Pediatrics',
//                     'medicine_otolaryngology'       => 'College of Medicine - ENT',
//                     'medicine_family-medicine'      => 'College of Medicine - Family Medicine',
//                     'medicine_orthopaedic-surgery'  => 'College of Medicine - Orthopaedics',
//                     'medicine_pathology'            => 'College of Medicine - Pathology',
//                     'medicine_urology'              => 'College of Medicine - Urology',
//                     'nursing'               => 'College of Nursing',
//                     'pharmacy'              => 'College of Pharmacy',
//                     'pharmacy_arpoison'     => 'College of Pharmacy - Arkansas Poison and Drug Information Center',
//                     'public-health'         => 'College of Publice Health',
//                     'grad-school'           => 'Graduate school',
//                     '12th-st'               => '12th St. Health & Wellness Center',
//                     'cda'                   => 'Center for Diversity Affairs',
//                     'health-literacy'       => 'Center for Health Literacy',
//                     'continuing-ed'         => 'Continuing Education',
//                     'get-healthy'           => 'Get Healthy UAMS',
//                     'gsa'                   => 'Graduate Student Association',
//                     'ipe'                   => 'Office of Interprofessional Education',
//                     'library'               => 'Library',
//                     'employee_nurses'       => 'Nurses (Employee)',
//                     'main'                  => 'Main UAMS site',
//                     'none'                  => 'None of the above',
//                 ),
//                 'js_options'      => array(
//                     'width' => '90%',
//                 ),
//                 'visible' => array( 'uamswp_location', '=', 'uams' ),
//             ),

//             array(
//                 'id'             => 'uamswp_uamshealth_subsite',
//                 'name'           => 'Organization',
//                 'type'            => 'select_advanced',
//                 'placeholder'     => 'Select an organization',
//                 // Array of 'value' => 'Label' pairs
//                 'options'         => array(
//                     'uams-aux'           => 'UAMS Auxiliary',
//                     'none'               => 'None of the above',
//                 ),
//                 'visible' => array( 'uamswp_template', '=', 'health' ),
//             ),

//             array(
//                 'id'             => 'uamswp_inside_subsite',
//                 'name'           => 'Organization',
//                 'type'            => 'select_advanced',
//                 'placeholder'     => 'Select an organization',
//                 // Array of 'value' => 'Label' pairs
//                 'options'         => array(
//                     'fitness-center'     => 'Fitness Center',
//                     'none'               => 'None of the above',
//                 ),
//                 'visible' => array( 'uamswp_template', '=', 'inside' ),
//             ),

//             array(
//                 'type' => 'heading',
//                 'name' => 'Custom Address',
//                 'desc' => 'Custom address(s), if needed',
//                 'hidden' => array( 
//                     array('uamswp_template', '!=', 'institute'),
//                     array('uamswp_location', '=', 'uams'),
//                 ),
//             ),

//             array(
//                 'id'           => 'uamswp_address',
//                 'title'        => 'Custom Address',
//                 // 'tab'       => 'faq',
//                 'type'         => 'group',
//                 'clone'        => true,
//                 'collapsible'  => true,
//                 'sort_clone'   => true,
//                 'group_title'  => array( 'field' => 'address_title' ),
//                 'max_clone'    => '2',
//                 'fields' => array(
//                     array(
//                         'name' => 'Address Name',
//                         'id'   => 'address_title',
//                         'type' => 'text',
//                         'description'   => 'Leave blank for a single address',
//                         'placeholder' => 'Mailing Address',
//                     ),
//                     array(
//                         'name' => 'Address',
//                         'id'   => 'address_street_1',
//                         'type' => 'text',
//                         'placeholder' => '4301 West Markham St #123',
//                     ),
//                     array(
//                         'name' => 'Address (2)',
//                         'id'   => 'address_street_2',
//                         'type' => 'text',
//                     ),
//                     array(
//                         'name' => 'City',
//                         'id'   => 'address_city',
//                         'type' => 'text',
//                         'placeholder' => 'Little Rock',
//                     ),
//                     array(
//                         'name' => 'State',
//                         'id'   => 'address_state',
//                         'type' => 'select',
//                         'options' =>       array (
//                             'AL' => 'Alabama',
//                             'AK' => 'Alaska',
//                             'AZ' => 'Arizona',
//                             'AR' => 'Arkansas',
//                             'CA' => 'California',
//                             'CO' => 'Colorado',
//                             'CT' => 'Connecticut',
//                             'DE' => 'Delaware',
//                             'DC' => 'District Of Columbia',
//                             'FL' => 'Florida',
//                             'GA' => 'Georgia',
//                             'HI' => 'Hawaii',
//                             'ID' => 'Idaho',
//                             'IL' => 'Illinois',
//                             'IN' => 'Indiana',
//                             'IA' => 'Iowa',
//                             'KS' => 'Kansas',
//                             'KY' => 'Kentucky',
//                             'LA' => 'Louisiana',
//                             'ME' => 'Maine',
//                             'MD' => 'Maryland',
//                             'MA' => 'Massachusetts',
//                             'MI' => 'Michigan',
//                             'MN' => 'Minnesota',
//                             'MS' => 'Mississippi',
//                             'MO' => 'Missouri',
//                             'MT' => 'Montana',
//                             'NE' => 'Nebraska',
//                             'NV' => 'Nevada',
//                             'NH' => 'New Hampshire',
//                             'NJ' => 'New Jersey',
//                             'NM' => 'New Mexico',
//                             'NY' => 'New York',
//                             'NC' => 'North Carolina',
//                             'ND' => 'North Dakota',
//                             'OH' => 'Ohio',
//                             'OK' => 'Oklahoma',
//                             'OR' => 'Oregon',
//                             'PA' => 'Pennsylvania',
//                             'RI' => 'Rhode Island',
//                             'SC' => 'South Carolina',
//                             'SD' => 'South Dakota',
//                             'TN' => 'Tennessee',
//                             'TX' => 'Texas',
//                             'UT' => 'Utah',
//                             'VT' => 'Vermont',
//                             'VA' => 'Virginia',
//                             'WA' => 'Washington',
//                             'WV' => 'West Virginia',
//                             'WI' => 'Wisconsin',
//                             'WY' => 'Wyoming',
//                           ),
//                           'std' =>       array (
//                              'AR',
//                           ),

//                     ),
//                     array(
//                         'name' => 'Zip',
//                         'id'   => 'address_zip',
//                         'type' => 'text',
//                         'size' => '10',
//                         'placeholder' => '72205',
//                     ),
//                 ),
//                 'hidden' => array( 
//                     array('uamswp_template', '!=', 'institute'),
//                     array('uamswp_location', '=', 'uams'),
//                 ),
//             ),
//         ),
//     );

//     $meta_boxes[] = array(
//         'id'             => 'uamswp_phone',
//         'title'          => 'Phone Number',
//         'settings_pages' => 'uamswp_options',
//         //'tab'            => 'faq',
//         'fields'         => array(
//             array(
//                 'type' => 'custom_html',
//                 'std'  => 'These will override the default social media',
//             ),
//             array(
//                 'id' => 'uamswp_primary_phone',
//           	    'type' => 'tel',
//                 'name' => 'Primary Phone #',
//                 'placeholder' => '(501) 686-7000',
//             ),
//             array(
//                 'id' => 'uamswp_add_phones',
//           	    'type' => 'url',
//                 'name' => 'Additional Phone Number(s) [URL]',
//                 'desc' => 'include http:// or https://'
//             ),
//         ),
//         'validation' => array(
// 		    'rules'  => array(
// 		        'uamswp_primary_phone' => array(
// 		            'required'  => false,
// 		            'phoneUS' => true,
// 		        ),
//             ),
//         ),
//     );

//     // $meta_boxes[] = array(
//     //     'id'             => 'uamswp_social',
//     //     'title'          => 'Social Media',
//     //     'settings_pages' => 'uamswp_options',
//     //     //'tab'            => 'faq',
//     //     'fields'         => array(
//     //         array(
//     //             'type' => 'custom_html',
//     //             'std'  => 'These will override the default social media',
//     //         ),
//     //         array(
//     //             'id' => 'uamswp_facebook',
//     //       	    'type' => 'url',
//     //       	    'name' => 'Facebook URL',
//     //         ),
//     //         array(
//     //             'id' => 'uamswp_twitter',
//     //       	    'type' => 'url',
//     //       	    'name' => 'Twitter URL',
//     //         ),
//     //         array(
//     //             'id' => 'uamswp_instagram',
//     //       	    'type' => 'url',
//     //       	    'name' => 'Instagram URL',
//     //         ),
//     //         array(
//     //             'id' => 'uamswp_youtube',
//     //       	    'type' => 'url',
//     //       	    'name' => 'YouTube URL',
//     //         ),
//     //         array(
//     //             'id' => 'uamswp_linkedin',
//     //       	    'type' => 'url',
//     //       	    'name' => 'LinkedIn URL',
//     //         ),
//     //         array(
//     //             'id' => 'uamswp_pinterest',
//     //       	    'type' => 'url',
//     //       	    'name' => 'Pinterest URL',
//     //         ),
//     //     ),
//     // );

//     $meta_boxes[] = array(
//         'id'             => 'info',
//         'title'          => 'Theme Info',
//         'settings_pages' => 'uamswp_options',
//         'context'        => 'side',
//         'fields'         => array(
//             array(
//                 'type' => 'custom_html',
//                 'std'  => 'Having questions? Check out our documentation',
//             ),
//         ),
//     );
//     return $meta_boxes;
// }

add_filter('acf/settings/show_admin', 'my_acf_show_admin');

function my_acf_show_admin( $show ) {
    
    return current_user_can('manage_options');
    
}

if( function_exists('acf_add_options_page') ) {
	
	acf_add_options_page(array(
		'page_title' 	=> 'UAMS Settings',
		'menu_title'	=> 'UAMS Settings',
		'menu_slug' 	=> 'uamswp-settings',
		'capability'	=> 'edit_posts',
        'redirect'		=> false,
        'autoload'      => true,
        'update_button'		=> __('Save Settings', 'acf'),
        'updated_message'	=> __("Settings Updated", 'acf'),
    ));

}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_uams_theme_settings',
	'title' => 'Theme Settings',
	'fields' => array(
		array(
			'key' => 'field_template',
			'label' => 'Theme Style',
			'name' => 'uamswp_template',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'choices' => array(
				'uams' => 'UAMS.edu',
				'health' => 'UAMSHealth',
				'inside' => 'Inside',
				'institute' => 'Institute',
			),
			'default_value' => array(
				0 => 'uams',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_location',
			'label' => 'Site Location',
			'name' => 'uamswp_location',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'uams',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'choices' => array(
				'uams' => 'Main Campus',
				'nw-campus' => 'Northwest Campus',
				'regional-campus-e' => 'Regional Campus - East',
				'regional-campus-ne' => 'Regional Campus - Northeast',
				'regional-campus-nw' => 'Regional Campus - Northwest',
				'regional-campus-nc' => 'Regional Campus - North Central',
				'regional-campus-s' => 'Regional Campus - South',
				'regional-campus-sw' => 'Regional Campus - Southwest',
				'regional-campus-sc' => 'Regional Campus - South Central',
				'regional-campus-w' => 'Regional Campus - West',
			),
			'default_value' => array(
				0 => 'uams',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_institute',
			'label' => 'UAMS Institute',
			'name' => 'uamswp_institute',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'institute',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'choices' => array(
				'institute_aging' => 'Donald W. Reynolds Institute on Aging',
				'institute_eye' => 'Harvey & Bernice Jones Eye Institute',
				'institute_spine' => 'Jackson T. Stephens Spine & Neurosciences Institute',
				'institute_digi-health' => 'Institute for Digital Health & Innovation',
				'institute_pri' => 'Psychiatric Research Institute',
				'institute_tri' => 'Translational Research Institute',
				'institute_cancer' => 'Winthrop P. Rockefeller Cancer Institute',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_uams_subsite',
			'label' => 'Organization',
			'name' => 'uamswp_uams_subsite',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_location',
						'operator' => '==',
						'value' => 'uams',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'choices' => array(
				'health-prof' => 'College of Health Professions',
				'medicine' => 'College of Medicine',
				'medicine_emergency-medicine' => 'College of Medicine -	Emergency Medicine',
				'medicine_pediatrics' => 'College of Medicine - Pediatrics',
				'medicine_otolaryngology' => 'College of Medicine - ENT',
				'medicine_family-medicine' => 'College of Medicine - Family Medicine',
				'medicine_orthopaedic-surgery' => 'College of Medicine - Orthopaedics',
				'medicine_pathology' => 'College of Medicine - Pathology',
				'medicine_urology' => 'College of Medicine - Urology',
				'nursing' => 'College of Nursing',
				'pharmacy' => 'College of Pharmacy',
				'pharmacy_arpoison' => 'College of Pharmacy - Arkansas Poison and Drug Information Center',
				'public-health' => 'College of Publice Health',
				'grad-school' => 'Graduate school',
				'12th-st' => '12th St. Health & Wellness Center',
				'cda' => 'Center for Diversity Affairs',
				'health-literacy' => 'Center for Health Literacy',
				'continuing-ed' => 'Continuing Education',
				'get-healthy' => 'Get Healthy UAMS',
				'gsa' => 'Graduate Student Association',
				'ipe' => 'Office of Interprofessional Education',
				'library' => 'Library',
				'employee_nurses' => 'Nurses (Employee)',
				'main' => 'Main UAMS site',
				'none' => 'None of the above',
			),
			'default_value' => array(
				0 => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_uamshealth_subsite',
			'label' => 'Organization',
			'name' => 'uamswp_uamshealth_subsite',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'health',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'choices' => array(
				'uams-aux' => 'UAMS Auxiliary',
				'none' => 'None of the above',
			),
			'default_value' => array(
				0 => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_inside_subsite',
			'label' => 'Organization',
			'name' => 'uamswp_inside_subsite',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'inside',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'choices' => array(
				'fitness-center' => 'Fitness Center',
				'none' => 'None of the above',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_address_accordion',
			'label' => 'Custom Addresses',
			'name' => '',
			'type' => 'accordion',
			'instructions' => 'Custom address(s), if needed',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'institute',
					),
				),
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'uams',
					),
					array(
						'field' => 'field_location',
						'operator' => '!=',
						'value' => 'uams',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_address',
			'label' => 'Custom Address',
			'name' => 'uamswp_address',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'institute',
					),
				),
				array(
					array(
						'field' => 'field_template',
						'operator' => '==',
						'value' => 'uams',
					),
					array(
						'field' => 'field_location',
						'operator' => '!=',
						'value' => 'uams',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => 'field_5ced844860649',
			'min' => 1,
			'max' => 2,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_address_title',
					'label' => 'Address Name',
					'name' => 'address_title',
					'type' => 'text',
					'instructions' => 'Leave blank for a single address',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => 'Mailing Address',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_address_street_1',
					'label' => 'Address',
					'name' => 'address_street_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '4301 West Markham St #123',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_address_street_2',
					'label' => 'Address (2)',
					'name' => 'address_street_2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_address_city',
					'label' => 'City',
					'name' => 'address_city',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_address_state',
					'label' => 'State',
					'name' => 'address_state',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
					'acfe_permissions' => '',
					'choices' => array(
						'AL' => 'Alabama',
						'AK' => 'Alaska',
						'AZ' => 'Arizona',
						'AR' => 'Arkansas',
						'CA' => 'California',
						'CO' => 'Colorado',
						'CT' => 'Connecticut',
						'DE' => 'Delaware',
						'DC' => 'District of Columbia',
						'FL' => 'Florida',
						'GA' => 'Georgia',
						'HI' => 'Hawaii',
						'ID' => 'Idaho',
						'IL' => 'Illinois',
						'IN' => 'Indiana',
						'IA' => 'Iowa',
						'KS' => 'Kansas',
						'KY' => 'Kentucky',
						'LA' => 'Louisiana',
						'ME' => 'Maine',
						'MD' => 'Maryland',
						'MA' => 'Massachusetts',
						'MI' => 'Michigan',
						'MN' => 'Minnesota',
						'MS' => 'Mississippi',
						'MO' => 'Missouri',
						'MT' => 'Montana',
						'NE' => 'Nebraska',
						'NV' => 'Nevada',
						'NH' => 'New Hampshire',
						'NJ' => 'New Jersey',
						'NM' => 'New Mexico',
						'NY' => 'New York',
						'NC' => 'North Carolina',
						'ND' => 'North Dakota',
						'OH' => 'Ohio',
						'OK' => 'Oklahoma',
						'OR' => 'Oregon',
						'PA' => 'Pennsylvania',
						'RI' => 'Rhode Island',
						'SC' => 'South Carolina',
						'SD' => 'South Dakota',
						'TN' => 'Tennessee',
						'TX' => 'Texas',
						'UT' => 'Utah',
						'VT' => 'Vermont',
						'VA' => 'Virginia',
						'WA' => 'Washington',
						'WV' => 'West Virginia',
						'WI' => 'Wisconsin',
						'WY' => 'Wyoming',
					),
					'default_value' => array(
						0 => 'AR',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_address_zip',
					'label' => 'Zip',
					'name' => 'address_zip',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
        ),
        array(
			'key' => 'field_phone_accordion',
			'label' => 'Phone Number',
			'name' => '',
			'type' => 'accordion',
			'instructions' => 'This will override the default phone number',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_uamswp_phone',
			'label' => 'Phone Number',
            'name' => 'uamswp_phone',
            'type' => (class_exists('jony_acf_plugin_intl_tel_input') ? 'intl_tel_input' : 'text'), // Telephone input
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'separateDialCode' => 0,
			'allowDropdown' => 0,
			'initialCountry' => 'us',
			'excludeCountries' => '',
			'onlyCountries' => '',
			'preferredCountries' => '',
		),
		array(
			'key' => 'field_uamswp_add_phones',
			'label' => 'Additional Phone Number(s) [Link]',
			'name' => 'uamswp_add_phones',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
        ),
        array(
			'key' => 'field_phone_accordion_end',
			'label' => 'Phone End',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 1,
		),
		array(
			'key' => 'field_submit_button',
			'label' => '',
			'name' => '',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'acfe_permissions' => '',
			'button_value' => 'Save',
			'button_attributes' => array(
				'button_type' => 'submit',
				'button_class' => 'button button-primary button-large',
				'button_id' => '',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'uamswp-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'active' => true,
));

acf_add_local_field_group(array(
	'key' => 'group_5d1263f48f6fb',
	'title' => 'UAMS Modules',
	'fields' => array(
		array(
			'key' => 'field_5d12642ac616f',
			'label' => 'Modules',
			'name' => 'uamswp_modules',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_flexible_stylised_button' => 1,
			'acfe_flexible_layouts_thumbnails' => 1,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '0',
			),
			'acfe_flexible_layouts_state' => 'collapse',
			'layouts' => array(
				'layout_5d126463e2192' => array(
					'key' => 'layout_5d126463e2192',
					'name' => 'modules_heading',
					'label' => 'Heading',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1264edc6170',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d126541c6171' => array(
					'key' => 'layout_5d126541c6171',
					'name' => 'modules_hero',
					'label' => 'Hero',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d126554c6172',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d12656bc6173' => array(
					'key' => 'layout_5d12656bc6173',
					'name' => 'modules_image_side',
					'label' => 'Side-by-side Image & Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d12656bc6174',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						// array(
						// 	'key' => 'm_field_side_image_intro-message',
						// 	'label' => '',
						// 	'name' => '',
						// 	'type' => 'message',
						// 	'instructions' => '',
						// 	'required' => 0,
						// 	'conditional_logic' => 0,
						// 	'wrapper' => array(
						// 		'width' => '',
						// 		'class' => '',
						// 		'id' => '',
						// 	),
						// 	'message' => '<h2>Side-by-Side Image & Text</h2>',
						// 	'new_lines' => 'wpautop',
						// 	'esc_html' => 0,
						// ),
						array(
							'key' => 'm_field_side_text-layout',
							'label' => 'Choose Text Layout',
							'name' => 'side_text-layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'body-only' => 'Body only',
								'link-list' => 'Body and Link List',
							),
							'default_value' => array(
								0 => 'body-only',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'm_field_side_heading',
							'label' => 'Heading',
							'name' => 'side_heading',
							'type' => 'text',
							'instructions' => '50 character limit.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => 50,
						),
						array(
							'key' => 'm_field_side_layout-body-only_body',
							'label' => 'Body',
							'name' => 'side_layout-body-only_body',
							'type' => 'textarea',
							'instructions' => '449 character limit.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'm_field_side_text-layout',
										'operator' => '==',
										'value' => 'body-only',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => 449,
							'rows' => 6,
							'new_lines' => '',
						),
						array(
							'key' => 'm_field_side_layout-link-list_body',
							'label' => 'Body',
							'name' => 'side_layout-link-list_body',
							'type' => 'textarea',
							'instructions' => '172 character limit.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'm_field_side_text-layout',
										'operator' => '==',
										'value' => 'link-list',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => 172,
							'rows' => 3,
							'new_lines' => '',
						),
						array(
							'key' => 'm_field_side_link-list',
							'label' => 'Link List',
							'name' => 'side_link-list',
							'type' => 'repeater',
							'instructions' => 'You may add up to six links. However, if you add a sixth link, the option for adding "and more" in the sixth position will be disabled.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'm_field_side_text-layout',
										'operator' => '==',
										'value' => 'link-list',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'm_field_side_link-list_text',
							'min' => 1,
							'max' => 6,
							'layout' => 'block',
							'button_label' => 'Add Link',
							'sub_fields' => array(
								array(
									'key' => 'm_field_side_link-list_text',
									'label' => 'Link Text',
									'name' => 'side_link-list_text',
									'type' => 'text',
									'instructions' => '40 character limit.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => 40,
								),
								array(
									'key' => 'm_field_side_link-list_url',
									'label' => 'Link URL',
									'name' => 'side_link-list_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'm_field_side_link-list_description',
									'label' => 'Link Description',
									'name' => 'side_link-list_description',
									'type' => 'text',
									'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'm_field_side_link-list_include-more',
							'label' => 'Include "and more" at the end of the Link List?',
							'name' => 'side_link-list_include-more',
							'type' => 'true_false',
							'instructions' => 'This option is only available if you have 1-5 items in the link list.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'm_field_side_link-list',
										'operator' => '<',
										'value' => '6',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'm_field_side_cta',
							'label' => 'Call to Action Button',
							'name' => 'side_cta',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'm_field_side_cta_text',
									'label' => 'Button Text',
									'name' => 'side_cta_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'm_field_side_cta_url',
									'label' => 'Button URL',
									'name' => 'side_cta_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'm_field_side_cta_target',
									'label' => 'Open in New Window?',
									'name' => 'side_cta_target',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'm_field_side_cta_description',
									'label' => 'Link Description',
									'name' => 'side_cta_description',
									'type' => 'text',
									'instructions' => 'This is needed for accessibility. It helps differentiate between multiple links that use the same text like "Learn more". Describe the intent of the link, like "Learn more about the ABC Department".',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'm_field_side_image',
							'label' => 'Image Options',
							'name' => 'side_image',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'm_field_side_image_image',
									'label' => 'Image',
									'name' => 'side_image_image',
									'type' => 'image',
									'instructions' => 'Recommended image dimensions: 5120x2880. Minimum image dimensions: 1920x1080. The image will be automatically cropped to a 16:9 aspect ratio.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => 1920,
									'min_height' => 1080,
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'm_field_side_image_alt-text',
									'label' => 'Image Alt Text Override',
									'name' => 'side_image_alt-text',
									'type' => 'text',
									'instructions' => 'Alt text (alternative text) refers to invisible description of images which are read aloud to blind users on a screen reader. If you want to define alt text that is different from the alt text defined for this image in the media library, you can do so here.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => 125,
								),
								array(
									'key' => 'm_field_side_image_crop',
									'label' => 'Vertical Crop',
									'name' => 'side_image_crop',
									'type' => 'select',
									'instructions' => 'Your image will be cropped if necessary. Tell us if we should crop it from the top, middle, or bottom.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'top' => 'Crop from Top',
										'center' => 'Crop from Center',
										'bottom' => 'Crop from Bottom',
									),
									'default_value' => array(
										0 => 'center',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'm_field_side_image_position',
							'label' => 'Image & Text Position',
							'name' => 'side_image_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Image on Left, Text on Right',
								'right' => 'Image on Right, Text on Left',
							),
							'default_value' => array(
								0 => 'left',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'm_field_side_image_anchor',
							'label' => 'Image Anchor Position',
							'name' => 'side_image_anchor',
							'type' => 'button_group',
							'instructions' => 'Where is the focus of your image content?',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'center' => 'Center',
								'right' => 'Right',
							),
							'allow_null' => 0,
							'default_value' => 'center',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'm_field_side_image_background-color',
							'label' => 'Background Color',
							'name' => 'side_image_background-color',
							'type' => 'select',
							'instructions' => 'This defines the background color of the text container.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-gray' => 'Gray',
							),
							'default_value' => array(
								0 => 'bg-white',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d126591c6175' => array(
					'key' => 'layout_5d126591c6175',
					'name' => 'modules_text_stacked',
					'label' => 'Stacked Image & Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d126591c6176',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1265acc6177' => array(
					'key' => 'layout_5d1265acc6177',
					'name' => 'modules_text_overlay',
					'label' => 'Text & Image Overlay',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1265acc6178',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1265ccc6179' => array(
					'key' => 'layout_5d1265ccc6179',
					'name' => 'modules_cta',
					'label' => 'Call-to-Action (CTA) Bar',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1265ccc617a',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1265e1c617b' => array(
					'key' => 'layout_5d1265e1c617b',
					'name' => 'modules_call_out',
					'label' => 'Call-Out',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1265e1c617c',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1265f2c617d' => array(
					'key' => 'layout_5d1265f2c617d',
					'name' => 'modules_action_bar',
					'label' => 'Action Bar',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1265f2c617e',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d126609c617f' => array(
					'key' => 'layout_5d126609c617f',
					'name' => 'modules_post_tiles',
					'label' => 'Post Category Tile (Double)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d126609c6180',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d126626c6181' => array(
					'key' => 'layout_5d126626c6181',
					'name' => 'modules_post_tile',
					'label' => 'Post Category Tile (Single)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d126626c6182',
							'label' => 'Section Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Module',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/modules.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_permissions' => '',
	'acfe_note' => '',
	'acfcdt_manage_table_definition' => 0,
	'acfcdt_table_definition_file_name' => 'table_613x5d1263f5763bb',
	'acfe_meta' => '',
));

endif;